import type {
  Prisma,
  RatchetDispatchOutcome,
  Workspace,
  WorkspaceProviderSelection,
} from '@prisma-gen/client';
import { prisma } from '@/backend/db';
import type {
  PRDiscoveryClaim,
  PRSnapshotFields,
  WorkspaceFixerContext,
  WorkspacePRContext,
  WorkspaceProviderSelectionSnapshot,
  WorkspaceStatusSnapshot,
} from '@/backend/services/workspace/types';
import type {
  AutoIterationStatus,
  CIStatus,
  PRState,
  RatchetState,
  RunScriptStatus,
  WorkspaceStatus,
} from '@/shared/core';
import { KanbanColumn } from '@/shared/core';

const autoIterationExecutionContextSelect = {
  worktreePath: true,
  autoIterationSessionId: true,
} satisfies Prisma.WorkspaceSelect;

const runScriptExecutionStateSelect = {
  runScriptStatus: true,
  runScriptPid: true,
  runScriptPort: true,
  runScriptStartedAt: true,
} satisfies Prisma.WorkspaceSelect;

export type AutoIterationExecutionContext = Prisma.WorkspaceGetPayload<{
  select: typeof autoIterationExecutionContextSelect;
}>;

export type RunScriptExecutionState = Prisma.WorkspaceGetPayload<{
  select: typeof runScriptExecutionStateSelect;
}>;

/**
 * Threshold for considering a PROVISIONING workspace as stale.
 * Workspaces in PROVISIONING state for longer than this are considered
 * stuck (e.g., due to server crash) and will be recovered by reconciliation.
 */
const STALE_PROVISIONING_THRESHOLD_MS = 10 * 60 * 1000; // 10 minutes

/**
 * Threshold for considering an ARCHIVING workspace as stale.
 * ARCHIVING is a persisted transient state; after this threshold, no
 * in-flight archive from the current process should still be active.
 */
const STALE_ARCHIVING_THRESHOLD_MS = 10 * 60 * 1000; // 10 minutes

interface CreateWorkspaceInput {
  projectId: string;
  name: string;
  description?: string;
  branchName?: string;
  githubIssueNumber?: number;
  githubIssueUrl?: string;
  linearIssueId?: string;
  linearIssueIdentifier?: string;
  linearIssueUrl?: string;
  isAutoGeneratedBranch?: boolean;
  ratchetEnabled?: boolean;
  defaultSessionProvider?: Prisma.WorkspaceCreateInput['defaultSessionProvider'];
  ratchetSessionProvider?: Prisma.WorkspaceCreateInput['ratchetSessionProvider'];
  creationSource?:
    | 'MANUAL'
    | 'RESUME_BRANCH'
    | 'GITHUB_ISSUE'
    | 'LINEAR_ISSUE'
    | 'PERIODIC_TASK'
    | 'CHILD_WORKSPACE';
  creationMetadata?: Prisma.InputJsonValue;
  mode?: 'STANDARD' | 'AUTO_ITERATION';
  autoIterationConfig?: Prisma.InputJsonValue;
  periodicTaskId?: string;
  parentWorkspaceId?: string;
}

interface UpdateWorkspaceInput {
  name?: string;
  description?: string;
  // Note: status changes must go through workspaceStateMachine, not direct updates
  worktreePath?: string | null;
  branchName?: string | null;
  isAutoGeneratedBranch?: boolean;
  prUrl?: string | null;
  githubIssueNumber?: number | null;
  githubIssueUrl?: string | null;
  // PR tracking fields
  prNumber?: number | null;
  prState?: PRState;
  prReviewState?: string | null;
  prCiStatus?: CIStatus;
  prUpdatedAt?: Date | null;
  prDiscoveryLastCheckedAt?: Date | null;
  prDiscoveryRetryCount?: number;
  prDiscoveryNextCheckAt?: Date | null;
  // CI failure tracking
  prCiFailedAt?: Date | null;
  prCiLastNotifiedAt?: Date | null;
  // PR Review tracking
  prReviewLastCheckedAt?: Date | null;
  prReviewLastCommentId?: string | null;
  // Ratchet tracking
  ratchetEnabled?: boolean;
  defaultSessionProvider?: Prisma.WorkspaceUpdateInput['defaultSessionProvider'];
  ratchetSessionProvider?: Prisma.WorkspaceUpdateInput['ratchetSessionProvider'];
  ratchetState?: RatchetState;
  ratchetLastCheckedAt?: Date | null;
  ratchetActiveSessionId?: string | null;
  ratchetLastCiRunId?: string | null;
  ratchetDispatchOutcome?: RatchetDispatchOutcome | null;
  ratchetDispatchRetryCount?: number;
  // Activity tracking
  hasHadSessions?: boolean;
  // Cached kanban column
  cachedKanbanColumn?: KanbanColumn;
  stateComputedAt?: Date | null;
  // Run script tracking
  runScriptCommand?: string | null;
  runScriptPostRunCommand?: string | null;
  runScriptCleanupCommand?: string | null;
  runScriptPid?: number | null;
  runScriptPort?: number | null;
  runScriptStartedAt?: Date | null;
  runScriptStatus?: RunScriptStatus;
  // Auto-iteration tracking
  autoIterationStatus?: Prisma.WorkspaceUpdateInput['autoIterationStatus'];
  autoIterationConfig?: Prisma.NullableJsonNullValueInput | Prisma.InputJsonValue;
  autoIterationProgress?: Prisma.NullableJsonNullValueInput | Prisma.InputJsonValue;
  autoIterationSessionId?: string | null;
}

export interface PrSnapshotPersistenceInput {
  prUrl?: string | null;
  prNumber: number;
  prState: PRState;
  prReviewState: string | null;
  prCiStatus: CIStatus;
  prUpdatedAt: Date;
  branchName?: string;
}

export interface CIObservationPersistenceInput {
  prCiStatus: CIStatus;
  prUpdatedAt: Date;
  prCiFailedAt?: Date | null;
}

export interface PrAggregatePersistenceResult {
  applied: boolean;
  dispatchReset: boolean;
}

type PrAggregatePersistenceInput = Partial<
  Pick<
    UpdateWorkspaceInput,
    | 'prUrl'
    | 'prNumber'
    | 'prState'
    | 'prReviewState'
    | 'prCiStatus'
    | 'prCiFailedAt'
    | 'branchName'
  >
> & { prUpdatedAt: Date };

export type KanbanOwnershipTuple = Pick<
  Workspace,
  | 'status'
  | 'prUrl'
  | 'prState'
  | 'prCiStatus'
  | 'prUpdatedAt'
  | 'ratchetEnabled'
  | 'ratchetState'
  | 'ratchetDispatchOutcome'
  | 'ratchetDispatchRetryCount'
  | 'cachedKanbanColumn'
>;

interface FindByProjectIdFilters {
  status?: WorkspaceStatus;
  excludeStatuses?: WorkspaceStatus[];
  kanbanColumn?: KanbanColumn;
  limit?: number;
  offset?: number;
}

type WorkspaceWithAgentSessions = Prisma.WorkspaceGetPayload<{
  include: { agentSessions: true; terminalSessions: true };
}>;

type WorkspaceForRatchet = {
  id: string;
  prUrl: string;
  prNumber: number | null;
  prState: PRState;
  prCiStatus: CIStatus;
  defaultSessionProvider: WorkspaceProviderSelection;
  ratchetSessionProvider: WorkspaceProviderSelection;
  ratchetEnabled: boolean;
  ratchetState: RatchetState;
  ratchetActiveSessionId: string | null;
  ratchetLastCiRunId: string | null;
  ratchetDispatchOutcome: RatchetDispatchOutcome | null;
  ratchetDispatchRetryCount: number;
  prReviewLastCheckedAt: Date | null;
};

export type WorkspaceWithSessions = WorkspaceWithAgentSessions;

// Type for Workspace with project included
type WorkspaceWithProject = Prisma.WorkspaceGetPayload<{
  include: { project: true };
}>;

type WorkspaceWithAgentSessionsAndProject = Prisma.WorkspaceGetPayload<{
  include: { agentSessions: true; terminalSessions: true; project: true };
}>;

// Type for Workspace with sessions and project included (used by reconciliation)
export type WorkspaceWithSessionsAndProject = WorkspaceWithAgentSessionsAndProject;

class WorkspaceAccessor {
  create(data: CreateWorkspaceInput): Promise<Workspace> {
    return prisma.workspace.create({
      data: {
        projectId: data.projectId,
        name: data.name,
        description: data.description,
        branchName: data.branchName,
        githubIssueNumber: data.githubIssueNumber,
        githubIssueUrl: data.githubIssueUrl,
        linearIssueId: data.linearIssueId,
        linearIssueIdentifier: data.linearIssueIdentifier,
        linearIssueUrl: data.linearIssueUrl,
        isAutoGeneratedBranch: data.isAutoGeneratedBranch ?? false,
        ratchetEnabled: data.ratchetEnabled,
        defaultSessionProvider: data.defaultSessionProvider,
        ratchetSessionProvider: data.ratchetSessionProvider,
        creationSource: data.creationSource,
        creationMetadata: data.creationMetadata,
        mode: data.mode,
        autoIterationConfig: data.autoIterationConfig,
        periodicTaskId: data.periodicTaskId,
        parentWorkspaceId: data.parentWorkspaceId,
      },
    });
  }

  findById(id: string): Promise<WorkspaceWithSessions | null> {
    return prisma.workspace.findUnique({
      where: { id },
      include: {
        agentSessions: true,
        terminalSessions: true,
      },
    });
  }

  /**
   * Find a workspace without relation includes.
   * Used by state machines that only need the raw row.
   */
  findRawById(id: string): Promise<Workspace | null> {
    return prisma.workspace.findUnique({
      where: { id },
    });
  }

  async exists(id: string): Promise<boolean> {
    const workspace = await prisma.workspace.findUnique({
      where: { id },
      select: { id: true },
    });
    return workspace !== null;
  }

  findProviderSelection(id: string): Promise<WorkspaceProviderSelectionSnapshot | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: {
        id: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
      },
    });
  }

  findFixerContext(id: string): Promise<WorkspaceFixerContext | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: {
        id: true,
        worktreePath: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
      },
    });
  }

  findStatusSnapshot(id: string): Promise<WorkspaceStatusSnapshot | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: {
        status: true,
        prUrl: true,
        prNumber: true,
        initCompletedAt: true,
      },
    });
  }

  findPRContext(id: string): Promise<WorkspacePRContext | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: { branchName: true, prUrl: true },
    });
  }

  /**
   * Find a workspace without relation includes and throw if missing.
   * Used by state machines after compare-and-swap updates.
   */
  findRawByIdOrThrow(id: string): Promise<Workspace> {
    return prisma.workspace.findUniqueOrThrow({
      where: { id },
    });
  }

  findAutoIterationExecutionContext(id: string): Promise<AutoIterationExecutionContext | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: autoIterationExecutionContextSelect,
    });
  }

  findRunScriptExecutionState(id: string): Promise<RunScriptExecutionState | null> {
    return prisma.workspace.findUnique({
      where: { id },
      select: runScriptExecutionStateSelect,
    });
  }

  findRunScriptExecutionStateOrThrow(id: string): Promise<RunScriptExecutionState> {
    return prisma.workspace.findUniqueOrThrow({
      where: { id },
      select: runScriptExecutionStateSelect,
    });
  }

  findByProjectId(projectId: string, filters?: FindByProjectIdFilters): Promise<Workspace[]> {
    const where: Prisma.WorkspaceWhereInput = { projectId };

    if (filters?.status) {
      where.status = filters.status;
    }

    if (filters?.kanbanColumn) {
      where.cachedKanbanColumn = filters.kanbanColumn;
    }

    return prisma.workspace.findMany({
      where,
      take: filters?.limit,
      skip: filters?.offset,
      orderBy: { updatedAt: 'desc' },
    });
  }

  /**
   * Find workspaces with sessions included (for kanban state computation).
   *
   * @throws Error if both status and excludeStatuses filters are specified
   */
  findByProjectIdWithSessions(
    projectId: string,
    filters?: FindByProjectIdFilters
  ): Promise<WorkspaceWithSessions[]> {
    // Validate mutually exclusive filters
    if (filters?.status && filters?.excludeStatuses?.length) {
      throw new Error('Cannot specify both status and excludeStatuses filters');
    }

    const where: Prisma.WorkspaceWhereInput = { projectId };

    if (filters?.status) {
      where.status = filters.status;
    }

    if (filters?.excludeStatuses && filters.excludeStatuses.length > 0) {
      where.status = { notIn: filters.excludeStatuses };
    }

    if (filters?.kanbanColumn) {
      where.cachedKanbanColumn = filters.kanbanColumn;
    }

    return prisma.workspace.findMany({
      where,
      take: filters?.limit,
      skip: filters?.offset,
      orderBy: { updatedAt: 'desc' },
      include: {
        agentSessions: true,
        terminalSessions: true,
      },
    });
  }

  /**
   * Find all non-archived workspaces with sessions and project included.
   * Used by the reconciliation service for single-query fetch of all workspace data.
   */
  findAllNonArchivedWithSessionsAndProject(): Promise<WorkspaceWithSessionsAndProject[]> {
    return prisma.workspace.findMany({
      where: { status: { not: 'ARCHIVED' } },
      include: {
        agentSessions: true,
        terminalSessions: true,
        project: true,
      },
      orderBy: { updatedAt: 'desc' },
    });
  }

  update(id: string, data: UpdateWorkspaceInput): Promise<Workspace> {
    return prisma.workspace.update({
      where: { id },
      data,
    });
  }

  async updateCachedKanbanColumnIfOwnershipMatches(
    id: string,
    expected: KanbanOwnershipTuple,
    data: Pick<UpdateWorkspaceInput, 'cachedKanbanColumn' | 'stateComputedAt'>
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: {
        id,
        status: expected.status,
        prUrl: expected.prUrl,
        prState: expected.prState,
        prCiStatus: expected.prCiStatus,
        prUpdatedAt: expected.prUpdatedAt,
        ratchetEnabled: expected.ratchetEnabled,
        ratchetState: expected.ratchetState,
        ratchetDispatchOutcome: expected.ratchetDispatchOutcome,
        ratchetDispatchRetryCount: expected.ratchetDispatchRetryCount,
        cachedKanbanColumn: expected.cachedKanbanColumn,
      },
      data,
    });
    return result.count === 1;
  }

  /**
   * Atomic compare-and-swap transition for workspace status.
   * Returns count=1 only when current status matches fromStatus.
   * Used to prevent race conditions in state transitions.
   */
  transitionWithCas(
    id: string,
    fromStatus: WorkspaceStatus,
    data: Prisma.WorkspaceUpdateManyMutationInput
  ): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: { id, status: fromStatus },
      data,
    });
  }

  /**
   * Compare-and-swap update for run script status transitions.
   * Returns count=1 only when current status matches.
   */
  casRunScriptStatusUpdate(
    id: string,
    currentStatus: RunScriptStatus,
    data: Prisma.WorkspaceUpdateManyMutationInput
  ): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: { id, runScriptStatus: currentStatus },
      data,
    });
  }

  async finishAutoIterationIfSessionMatches(
    id: string,
    sessionId: string,
    status: AutoIterationStatus
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id, autoIterationSessionId: sessionId },
      data: {
        autoIterationStatus: status,
        autoIterationSessionId: null,
      },
    });
    return result.count === 1;
  }

  async clearAutoIterationSessionIfMatches(id: string, sessionId: string): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id, autoIterationSessionId: sessionId },
      data: { autoIterationSessionId: null },
    });
    return result.count === 1;
  }

  /**
   * Find workspaces with auto-iteration status RUNNING and reset them to FAILED.
   * Called at server startup to recover states left in-flight by a server crash or restart.
   * The in-memory loop context is irrecoverably lost on restart, so FAILED (not PAUSED).
   */
  async resetStaleAutoIterationStatuses(): Promise<Array<{ id: string }>> {
    const stale = await prisma.workspace.findMany({
      where: { autoIterationStatus: 'RUNNING' },
      select: { id: true },
    });

    if (stale.length === 0) {
      return [];
    }

    await prisma.workspace.updateMany({
      where: {
        id: { in: stale.map((w) => w.id) },
        autoIterationStatus: 'RUNNING',
      },
      data: {
        autoIterationStatus: 'FAILED',
        autoIterationSessionId: null,
      },
    });

    return stale;
  }

  /**
   * Find workspaces with transient run script statuses (STARTING or STOPPING)
   * and reset them to IDLE. Called at server startup to recover states left
   * in-flight by a server crash or restart.
   * Returns the affected workspaces (id + prior status) for logging/event emission.
   */
  async resetStaleRunScriptStatuses(): Promise<
    Array<{ id: string; runScriptStatus: RunScriptStatus }>
  > {
    const stale = await prisma.workspace.findMany({
      where: { runScriptStatus: { in: ['STARTING', 'STOPPING'] } },
      select: { id: true, runScriptStatus: true },
    });

    if (stale.length === 0) {
      return [];
    }

    await prisma.workspace.updateMany({
      where: {
        id: { in: stale.map((w) => w.id) },
        runScriptStatus: { in: ['STARTING', 'STOPPING'] },
      },
      data: {
        runScriptStatus: 'IDLE',
        runScriptPid: null,
        runScriptPort: null,
        runScriptStartedAt: null,
      },
    });

    return stale;
  }

  /**
   * Conditional provisioning retry transition (FAILED -> PROVISIONING).
   * Returns count=1 when retry is allowed and transition was applied.
   */
  startProvisioningRetryIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'FAILED',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'PROVISIONING',
        cachedKanbanColumn: KanbanColumn.WORKING,
        stateComputedAt: new Date(),
        initRetryCount: { increment: 1 },
        initStartedAt: new Date(),
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  /**
   * Conditional provisioning retry transition (READY -> PROVISIONING).
   * Used when a workspace is READY+warning and the user retries the setup script.
   * Returns count=1 when retry is allowed and transition was applied.
   */
  startProvisioningFromReadyIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'READY',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'PROVISIONING',
        cachedKanbanColumn: KanbanColumn.WORKING,
        stateComputedAt: new Date(),
        initRetryCount: { increment: 1 },
        initStartedAt: new Date(),
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  /**
   * Conditional reset transition (FAILED -> NEW).
   * Returns count=1 when retry is allowed and transition was applied.
   */
  resetToNewIfAllowed(id: string, maxRetries: number): Promise<{ count: number }> {
    return prisma.workspace.updateMany({
      where: {
        id,
        status: 'FAILED',
        initRetryCount: { lt: maxRetries },
      },
      data: {
        status: 'NEW',
        cachedKanbanColumn: KanbanColumn.WORKING,
        stateComputedAt: new Date(),
        initRetryCount: { increment: 1 },
        initStartedAt: null,
        initCompletedAt: null,
        initErrorMessage: null,
        initScriptPid: null,
      },
    });
  }

  delete(id: string): Promise<Workspace> {
    return prisma.workspace.delete({
      where: { id },
    });
  }

  // Note: archive functionality is provided by workspaceStateMachine.archive()

  /**
   * Find workspaces that need worktree creation or recovery.
   * Returns:
   * - NEW workspaces that haven't started provisioning yet
   * - PROVISIONING workspaces that are stale (>10 minutes) and likely stuck due to server crash
   *
   * Used for reconciliation to ensure all workspaces are initialized.
   * Includes project for worktree creation.
   */
  findNeedingWorktree(): Promise<WorkspaceWithProject[]> {
    const staleThreshold = new Date(Date.now() - STALE_PROVISIONING_THRESHOLD_MS);

    return prisma.workspace.findMany({
      where: {
        OR: [
          { status: 'NEW' },
          {
            status: 'PROVISIONING',
            initStartedAt: { lt: staleThreshold },
          },
        ],
      },
      include: {
        project: true,
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Find ARCHIVING workspaces that have been stuck long enough to recover.
   * Includes project data so the archive workflow can safely clean up worktrees.
   */
  findStaleArchivingWithProject(): Promise<WorkspaceWithProject[]> {
    const staleThreshold = new Date(Date.now() - STALE_ARCHIVING_THRESHOLD_MS);

    return prisma.workspace.findMany({
      where: {
        status: 'ARCHIVING',
        updatedAt: { lt: staleThreshold },
      },
      include: {
        project: true,
      },
      orderBy: { updatedAt: 'asc' },
    });
  }

  /**
   * Find workspace by ID with project included.
   * Used when project info is needed (e.g., for worktree creation).
   */
  findByIdWithProject(id: string): Promise<WorkspaceWithProject | null> {
    return prisma.workspace.findUnique({
      where: { id },
      include: {
        project: true,
      },
    });
  }

  /**
   * Find READY workspaces with PR URLs that need sync.
   * Used for Inngest PR status sync job.
   */
  findNeedingPRSync(staleThresholdMinutes = 5): Promise<WorkspaceWithProject[]> {
    const staleThreshold = new Date(Date.now() - staleThresholdMinutes * 60 * 1000);

    return prisma.workspace.findMany({
      where: {
        status: 'READY',
        prUrl: { not: null },
        OR: [{ prUpdatedAt: null }, { prUpdatedAt: { lt: staleThreshold } }],
      },
      include: {
        project: true,
      },
      orderBy: { prUpdatedAt: 'asc' }, // Oldest first
    });
  }

  /**
   * Find READY workspaces without PR URLs that have a branch name.
   * Used for detecting newly created PRs.
   */
  findNeedingPRDiscovery(limit: number, dueAt = new Date()): Promise<WorkspaceWithProject[]> {
    return prisma.workspace.findMany({
      where: {
        status: 'READY',
        prUrl: null,
        branchName: { not: null },
        project: {
          githubOwner: { not: null },
          githubRepo: { not: null },
        },
        OR: [{ prDiscoveryNextCheckAt: null }, { prDiscoveryNextCheckAt: { lte: dueAt } }],
      },
      include: {
        project: true,
      },
      orderBy: [{ prDiscoveryNextCheckAt: 'asc' }, { updatedAt: 'desc' }],
      take: limit,
    });
  }

  /**
   * Claim a due PR discovery candidate using the values observed by the caller.
   * Concurrent activity or eligibility changes win by making this update a no-op.
   */
  async claimPRDiscoveryAttempt(
    id: string,
    attempt: {
      branchName: string;
      expectedUpdatedAt: Date;
      expectedRetryCount: number;
      expectedNextCheckAt: Date | null;
      checkedAt: Date;
      nextCheckAt: Date;
    }
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: {
        id,
        status: 'READY',
        prUrl: null,
        branchName: attempt.branchName,
        updatedAt: attempt.expectedUpdatedAt,
        prDiscoveryRetryCount: attempt.expectedRetryCount,
        prDiscoveryNextCheckAt: attempt.expectedNextCheckAt,
      },
      data: {
        prDiscoveryLastCheckedAt: attempt.checkedAt,
        prDiscoveryRetryCount: { increment: 1 },
        prDiscoveryNextCheckAt: attempt.nextCheckAt,
      },
    });
    return result.count > 0;
  }

  /**
   * Atomically attach a discovered PR only while the claim that produced it is
   * still current. A concurrent reset, branch rename, status change, or PR
   * attachment makes this update a no-op.
   */
  async attachDiscoveredPRIfClaimMatches(
    id: string,
    prUrl: string,
    claim: PRDiscoveryClaim,
    prUpdatedAt: Date
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: {
        id,
        status: 'READY',
        prUrl: null,
        branchName: claim.branchName,
        prDiscoveryLastCheckedAt: claim.checkedAt,
        prDiscoveryRetryCount: claim.retryCount,
        prDiscoveryNextCheckAt: claim.nextCheckAt,
      },
      data: {
        prUrl,
        prUpdatedAt,
      },
    });
    return result.count > 0;
  }

  /** Atomically update snapshot fields only while the expected PR remains attached. */
  async updatePRSnapshotIfUrlMatches(
    id: string,
    prUrl: string,
    snapshot: PRSnapshotFields,
    prUpdatedAt: Date
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id, prUrl },
      data: {
        ...snapshot,
        prUpdatedAt,
      },
    });
    return result.count > 0;
  }

  /** Make an eligible workspace immediately due for PR discovery again. */
  async resetPRDiscoveryBackoff(id: string): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: {
        id,
        status: 'READY',
        prUrl: null,
        branchName: { not: null },
      },
      data: {
        prDiscoveryLastCheckedAt: null,
        prDiscoveryRetryCount: 0,
        prDiscoveryNextCheckAt: null,
      },
    });
    return result.count > 0;
  }

  /**
   * Mark workspace as having had sessions (for kanban backlog/waiting distinction).
   * Uses atomic conditional update to prevent race conditions when multiple sessions start.
   */
  async markHasHadSessions(id: string): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, hasHadSessions: false },
      data: { hasHadSessions: true },
    });
  }

  /**
   * Settle the ratchet dispatch record when a fixer session ends. Conditional
   * on the pointer still naming this session, so whichever of the session-end
   * paths (lifecycle exit hook, deliberate stop, poll-check fallback) gets
   * here first wins and the others no-op — a check racing a normal exit can
   * never overwrite a COMPLETED outcome with DIED.
   */
  async recordRatchetSessionEnd(
    workspaceId: string,
    sessionId: string,
    outcome: Exclude<RatchetDispatchOutcome, 'RUNNING'>
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id: workspaceId, ratchetActiveSessionId: sessionId },
      data: { ratchetActiveSessionId: null, ratchetDispatchOutcome: outcome },
    });
    return result.count > 0;
  }

  /**
   * Persist a PR aggregate and clear ownership from a settled dispatch when
   * the newly fetched aggregate changed. The conditional update writes the
   * aggregate and reset atomically. The reset compares all dispatch metadata
   * read in the transaction; if a newer dispatch wins that race, only the PR
   * aggregate is written and its ownership is preserved. Identical periodic
   * refreshes use the plain snapshot update and leave settled metadata
   * untouched; RUNNING ownership is never eligible for the reset.
   * ratchetLastCiRunId deliberately remains the richer dispatch snapshot key;
   * the Ratchet still uses it to decide whether the changed aggregate warrants
   * another fixer.
   */
  applyPrSnapshotWithDispatchReset(
    workspaceId: string,
    observation: PrSnapshotPersistenceInput
  ): Promise<PrAggregatePersistenceResult> {
    return this.applyPrAggregateUpdateWithDispatchReset(workspaceId, observation);
  }

  applyCIObservationWithDispatchReset(
    workspaceId: string,
    observation: CIObservationPersistenceInput
  ): Promise<PrAggregatePersistenceResult> {
    return this.applyPrAggregateUpdateWithDispatchReset(workspaceId, observation);
  }

  private async applyPrAggregateUpdateWithDispatchReset(
    workspaceId: string,
    observation: PrAggregatePersistenceInput
  ): Promise<PrAggregatePersistenceResult> {
    const snapshotData: UpdateWorkspaceInput = {
      ...(observation.prUrl !== undefined ? { prUrl: observation.prUrl } : {}),
      ...(observation.prNumber !== undefined ? { prNumber: observation.prNumber } : {}),
      ...(observation.prState !== undefined ? { prState: observation.prState } : {}),
      ...(observation.prReviewState !== undefined
        ? { prReviewState: observation.prReviewState }
        : {}),
      ...(observation.prCiStatus !== undefined ? { prCiStatus: observation.prCiStatus } : {}),
      ...(observation.prCiFailedAt !== undefined ? { prCiFailedAt: observation.prCiFailedAt } : {}),
      prUpdatedAt: observation.prUpdatedAt,
      ...(observation.branchName !== undefined ? { branchName: observation.branchName } : {}),
    };
    return await prisma.$transaction(async (transaction) => {
      const current = await transaction.workspace.findUniqueOrThrow({
        where: { id: workspaceId },
        select: {
          prUrl: true,
          prNumber: true,
          prState: true,
          prReviewState: true,
          prCiStatus: true,
          prUpdatedAt: true,
          ratchetActiveSessionId: true,
          ratchetLastCiRunId: true,
          ratchetDispatchOutcome: true,
          ratchetDispatchRetryCount: true,
        },
      });
      const aggregateChanged =
        (observation.prNumber !== undefined && current.prNumber !== observation.prNumber) ||
        (observation.prState !== undefined && current.prState !== observation.prState) ||
        (observation.prReviewState !== undefined &&
          current.prReviewState !== observation.prReviewState) ||
        (observation.prCiStatus !== undefined && current.prCiStatus !== observation.prCiStatus) ||
        (observation.prUrl !== undefined && current.prUrl !== observation.prUrl);
      const shouldReset =
        aggregateChanged &&
        (current.ratchetDispatchOutcome === 'COMPLETED' ||
          current.ratchetDispatchOutcome === 'DIED');
      const aggregateGuard = {
        prUrl: current.prUrl,
        prNumber: current.prNumber,
        prState: current.prState,
        prReviewState: current.prReviewState,
        prCiStatus: current.prCiStatus,
        prUpdatedAt: current.prUpdatedAt,
      };

      if (shouldReset) {
        const reset = await transaction.workspace.updateMany({
          where: {
            id: workspaceId,
            ...aggregateGuard,
            ratchetActiveSessionId: current.ratchetActiveSessionId,
            ratchetLastCiRunId: current.ratchetLastCiRunId,
            ratchetDispatchOutcome: current.ratchetDispatchOutcome,
            ratchetDispatchRetryCount: current.ratchetDispatchRetryCount,
          },
          data: {
            ...snapshotData,
            ratchetDispatchOutcome: null,
            ratchetDispatchRetryCount: 0,
          },
        });
        if (reset.count > 0) {
          return { applied: true, dispatchReset: true };
        }
      }

      const fallback = await transaction.workspace.updateMany({
        where: { id: workspaceId, ...aggregateGuard },
        data: snapshotData,
      });
      return { applied: fallback.count > 0, dispatchReset: false };
    });
  }

  /**
   * Record a ratchet fixer dispatch (session pointer, snapshot key, RUNNING
   * outcome, retry count) atomically, only while ratcheting is still enabled.
   * The conditional update closes the disable-vs-dispatch race where an
   * in-flight ratchet check could repopulate the active session after disable.
   */
  async recordRatchetDispatchIfEnabled(
    workspaceId: string,
    dispatch: { sessionId: string; snapshotKey: string; retryCount: number }
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id: workspaceId, ratchetEnabled: true },
      data: {
        ratchetActiveSessionId: dispatch.sessionId,
        ratchetLastCiRunId: dispatch.snapshotKey,
        ratchetDispatchOutcome: 'RUNNING',
        ratchetDispatchRetryCount: dispatch.retryCount,
      },
    });
    return result.count > 0;
  }

  /**
   * Adopt an already-running fixer session as the active ratchet session
   * without recording a new dispatch (the snapshot key and retry count are
   * left untouched, since no prompt was sent for the current PR state).
   */
  async adoptRatchetActiveSessionIfEnabled(
    workspaceId: string,
    sessionId: string
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id: workspaceId, ratchetEnabled: true },
      data: { ratchetActiveSessionId: sessionId, ratchetDispatchOutcome: 'RUNNING' },
    });
    return result.count > 0;
  }

  /**
   * Compare-and-swap ratchet state transition, mirroring transitionWithCas.
   * Persists only while ratcheting remains enabled AND the state still matches
   * the fromState the caller observed, so stale in-flight checks can neither
   * overwrite the disabled state nor a concurrent transition, and emitted
   * fromState values are accurate by construction. Transition validity is
   * checked by the caller against RATCHET_VALID_TRANSITIONS (see
   * ratchet-state-machine.ts).
   */
  async transitionRatchetStateIfEnabled(
    workspaceId: string,
    fromState: RatchetState,
    data: Pick<UpdateWorkspaceInput, 'ratchetState' | 'ratchetLastCheckedAt'>
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id: workspaceId, ratchetEnabled: true, ratchetState: fromState },
      data,
    });
    return result.count > 0;
  }

  /**
   * Settle ratchet state to IDLE for a workspace whose ratcheting is disabled,
   * CAS on the fromState the caller observed. The disabled condition keeps
   * this write from clobbering a concurrent re-enable, and the fromState
   * condition keeps the emitted transition accurate.
   */
  async settleRatchetIdleWhileDisabled(
    workspaceId: string,
    fromState: RatchetState
  ): Promise<boolean> {
    const result = await prisma.workspace.updateMany({
      where: { id: workspaceId, ratchetEnabled: false, ratchetState: fromState },
      data: { ratchetState: 'IDLE', ratchetLastCheckedAt: new Date() },
    });
    return result.count > 0;
  }

  /**
   * Append output to initOutput field during startup script execution.
   * Truncates from the beginning if output exceeds maxSize to prevent unbounded growth.
   */
  async appendInitOutput(id: string, output: string, maxSize = 50 * 1024): Promise<void> {
    const truncationMarker = '[...truncated...]\n';
    const markerLength = truncationMarker.length;
    const now = new Date();
    const updatedRows = await prisma.$executeRaw`
      UPDATE "Workspace"
      SET "initOutput" = CASE
        WHEN length(COALESCE("initOutput", '') || ${output}) <= ${maxSize}
          THEN COALESCE("initOutput", '') || ${output}
        WHEN ${maxSize} <= ${markerLength}
          THEN substr(${truncationMarker}, 1, ${maxSize})
        ELSE ${truncationMarker} || substr(
          COALESCE("initOutput", '') || ${output},
          -(${maxSize} - ${markerLength})
        )
      END,
      "updatedAt" = ${now}
      WHERE "id" = ${id}
    `;

    if (Number(updatedRows) === 0) {
      const existing = await prisma.workspace.findUnique({
        where: { id },
        select: { id: true },
      });
      if (!existing) {
        throw new Error(`Workspace not found: ${id}`);
      }
    }
  }

  /**
   * Track the currently running startup/setup script process for provisioning recovery.
   */
  async setInitScriptPid(id: string, pid: number): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, status: 'PROVISIONING' },
      data: { initScriptPid: pid },
    });
  }

  /**
   * Clear startup/setup script process tracking if it still points to the given process.
   */
  async clearInitScriptPid(id: string, pid: number): Promise<void> {
    await prisma.workspace.updateMany({
      where: { id, initScriptPid: pid },
      data: { initScriptPid: null },
    });
  }

  /**
   * Clear initOutput field (called when retrying initialization).
   */
  async clearInitOutput(id: string): Promise<void> {
    await prisma.workspace.update({
      where: { id },
      data: { initOutput: null },
    });
  }

  /**
   * Find multiple workspaces by their IDs.
   * Used for batch lookups when enriching process info.
   */
  findByIds(ids: string[]): Promise<Workspace[]> {
    if (ids.length === 0) {
      return Promise.resolve([]);
    }
    return prisma.workspace.findMany({
      where: {
        id: { in: ids },
      },
    });
  }

  /**
   * Find multiple workspaces by their IDs with project included.
   * Used for batch lookups when project info is needed (e.g., admin process list).
   */
  findByIdsWithProject(ids: string[]): Promise<WorkspaceWithProject[]> {
    if (ids.length === 0) {
      return Promise.resolve([]);
    }
    return prisma.workspace.findMany({
      where: {
        id: { in: ids },
      },
      include: {
        project: true,
      },
    });
  }

  /**
   * Find READY workspaces with PR URLs for ratchet monitoring.
   * Returns workspaces that have PRs to monitor for progression.
   */
  findWithPRsForRatchet(): Promise<WorkspaceForRatchet[]> {
    return prisma.workspace.findMany({
      where: {
        status: 'READY',
        prUrl: { not: null },
        // Skip disabled and terminal workspaces to avoid unnecessary GitHub API calls.
        // Closed PRs are excluded via the cached prState (kept fresh by the scheduler
        // PR sync, which also flips it back to OPEN if the PR is reopened).
        ratchetEnabled: true,
        ratchetState: { not: 'MERGED' },
        prState: { not: 'CLOSED' },
      },
      select: {
        id: true,
        prUrl: true,
        prNumber: true,
        prState: true,
        prCiStatus: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
        ratchetEnabled: true,
        ratchetState: true,
        ratchetActiveSessionId: true,
        ratchetLastCiRunId: true,
        ratchetDispatchOutcome: true,
        ratchetDispatchRetryCount: true,
        prReviewLastCheckedAt: true,
      },
      orderBy: { ratchetLastCheckedAt: 'asc' }, // Check oldest first
    }) as Promise<WorkspaceForRatchet[]>;
  }

  /**
   * Find a single READY workspace with PR for ratchet processing.
   */
  findForRatchetById(id: string): Promise<WorkspaceForRatchet | null> {
    return prisma.workspace.findFirst({
      where: {
        id,
        status: 'READY',
        prUrl: { not: null },
      },
      select: {
        id: true,
        prUrl: true,
        prNumber: true,
        prState: true,
        prCiStatus: true,
        defaultSessionProvider: true,
        ratchetSessionProvider: true,
        ratchetEnabled: true,
        ratchetState: true,
        ratchetActiveSessionId: true,
        ratchetLastCiRunId: true,
        ratchetDispatchOutcome: true,
        ratchetDispatchRetryCount: true,
        prReviewLastCheckedAt: true,
      },
    }) as Promise<WorkspaceForRatchet | null>;
  }

  // ---------------------------------------------------------------------------
  // Parent / child workspace hierarchy
  // ---------------------------------------------------------------------------

  /**
   * Find non-archived child workspaces for a given parent.
   */
  findChildrenByParentId(parentId: string): Promise<Workspace[]> {
    return prisma.workspace.findMany({
      where: { parentWorkspaceId: parentId, status: { not: 'ARCHIVED' } },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Find child workspaces with session counts included, for status summaries.
   */
  findChildrenWithStatus(
    parentId: string
  ): Promise<Prisma.WorkspaceGetPayload<{ include: { agentSessions: true; project: true } }>[]> {
    return prisma.workspace.findMany({
      where: { parentWorkspaceId: parentId, status: { not: 'ARCHIVED' } },
      include: { agentSessions: true, project: true },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Find the parent workspace summary for a given child workspace id.
   * Returns the parent with project included for cross-project navigation.
   */
  findParentWorkspace(childId: string): Promise<WorkspaceWithProject | null> {
    return prisma.workspace.findFirst({
      where: { childWorkspaces: { some: { id: childId } } },
      include: { project: true },
    });
  }
}

export const workspaceAccessor = new WorkspaceAccessor();
