-- CreateTable
CREATE TABLE "PeriodicTask" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "prompt" TEXT NOT NULL,
    "cadence" TEXT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "nextRunAt" DATETIME NOT NULL,
    "lastRunAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PeriodicTask_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PeriodicTaskExecution" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "periodicTaskId" TEXT NOT NULL,
    "workspaceId" TEXT,
    "status" TEXT NOT NULL,
    "prUrl" TEXT,
    "prNumber" INTEGER,
    "errorMessage" TEXT,
    "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" DATETIME,
    CONSTRAINT "PeriodicTaskExecution_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PeriodicTaskExecution_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Workspace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "worktreePath" TEXT,
    "branchName" TEXT,
    "isAutoGeneratedBranch" BOOLEAN NOT NULL DEFAULT false,
    "creationSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "creationMetadata" JSONB,
    "initErrorMessage" TEXT,
    "initOutput" TEXT,
    "initStartedAt" DATETIME,
    "initCompletedAt" DATETIME,
    "initRetryCount" INTEGER NOT NULL DEFAULT 0,
    "runScriptCommand" TEXT,
    "runScriptPostRunCommand" TEXT,
    "runScriptCleanupCommand" TEXT,
    "runScriptPid" INTEGER,
    "runScriptPort" INTEGER,
    "runScriptStartedAt" DATETIME,
    "runScriptStatus" TEXT NOT NULL DEFAULT 'IDLE',
    "prUrl" TEXT,
    "githubIssueNumber" INTEGER,
    "githubIssueUrl" TEXT,
    "linearIssueId" TEXT,
    "linearIssueIdentifier" TEXT,
    "linearIssueUrl" TEXT,
    "defaultSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "ratchetSessionProvider" TEXT NOT NULL DEFAULT 'WORKSPACE_DEFAULT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "prNumber" INTEGER,
    "prState" TEXT NOT NULL DEFAULT 'NONE',
    "prReviewState" TEXT,
    "prCiStatus" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "prUpdatedAt" DATETIME,
    "prCiFailedAt" DATETIME,
    "prCiLastNotifiedAt" DATETIME,
    "prReviewLastCheckedAt" DATETIME,
    "prReviewLastCommentId" TEXT,
    "ratchetEnabled" BOOLEAN NOT NULL DEFAULT true,
    "ratchetState" TEXT NOT NULL DEFAULT 'IDLE',
    "ratchetLastCheckedAt" DATETIME,
    "ratchetActiveSessionId" TEXT,
    "ratchetLastCiRunId" TEXT,
    "mode" TEXT NOT NULL DEFAULT 'STANDARD',
    "autoIterationStatus" TEXT,
    "autoIterationConfig" JSONB,
    "autoIterationProgress" JSONB,
    "autoIterationSessionId" TEXT,
    "periodicTaskId" TEXT,
    "hasHadSessions" BOOLEAN NOT NULL DEFAULT false,
    "cachedKanbanColumn" TEXT NOT NULL DEFAULT 'WAITING',
    "stateComputedAt" DATETIME,
    CONSTRAINT "Workspace_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Workspace_periodicTaskId_fkey" FOREIGN KEY ("periodicTaskId") REFERENCES "PeriodicTask" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Workspace" ("autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "cachedKanbanColumn", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetActiveSessionId", "ratchetEnabled", "ratchetLastCheckedAt", "ratchetLastCiRunId", "ratchetSessionProvider", "ratchetState", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "stateComputedAt", "status", "updatedAt", "worktreePath") SELECT "autoIterationConfig", "autoIterationProgress", "autoIterationSessionId", "autoIterationStatus", "branchName", "cachedKanbanColumn", "createdAt", "creationMetadata", "creationSource", "defaultSessionProvider", "description", "githubIssueNumber", "githubIssueUrl", "hasHadSessions", "id", "initCompletedAt", "initErrorMessage", "initOutput", "initRetryCount", "initStartedAt", "isAutoGeneratedBranch", "linearIssueId", "linearIssueIdentifier", "linearIssueUrl", "mode", "name", "prCiFailedAt", "prCiLastNotifiedAt", "prCiStatus", "prNumber", "prReviewLastCheckedAt", "prReviewLastCommentId", "prReviewState", "prState", "prUpdatedAt", "prUrl", "projectId", "ratchetActiveSessionId", "ratchetEnabled", "ratchetLastCheckedAt", "ratchetLastCiRunId", "ratchetSessionProvider", "ratchetState", "runScriptCleanupCommand", "runScriptCommand", "runScriptPid", "runScriptPort", "runScriptPostRunCommand", "runScriptStartedAt", "runScriptStatus", "stateComputedAt", "status", "updatedAt", "worktreePath" FROM "Workspace";
DROP TABLE "Workspace";
ALTER TABLE "new_Workspace" RENAME TO "Workspace";
CREATE INDEX "Workspace_projectId_idx" ON "Workspace"("projectId");
CREATE INDEX "Workspace_status_idx" ON "Workspace"("status");
CREATE INDEX "Workspace_cachedKanbanColumn_idx" ON "Workspace"("cachedKanbanColumn");
CREATE INDEX "Workspace_projectId_status_idx" ON "Workspace"("projectId", "status");
CREATE INDEX "Workspace_projectId_cachedKanbanColumn_idx" ON "Workspace"("projectId", "cachedKanbanColumn");
CREATE INDEX "Workspace_projectId_updatedAt_idx" ON "Workspace"("projectId", "updatedAt");
CREATE INDEX "Workspace_projectId_createdAt_idx" ON "Workspace"("projectId", "createdAt");
CREATE INDEX "Workspace_status_prUrl_idx" ON "Workspace"("status", "prUrl");
CREATE INDEX "Workspace_status_prUpdatedAt_idx" ON "Workspace"("status", "prUpdatedAt");
CREATE INDEX "Workspace_status_ratchetEnabled_ratchetLastCheckedAt_idx" ON "Workspace"("status", "ratchetEnabled", "ratchetLastCheckedAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "PeriodicTask_projectId_idx" ON "PeriodicTask"("projectId");

-- CreateIndex
CREATE INDEX "PeriodicTask_isEnabled_nextRunAt_idx" ON "PeriodicTask"("isEnabled", "nextRunAt");

-- CreateIndex
CREATE UNIQUE INDEX "PeriodicTaskExecution_workspaceId_key" ON "PeriodicTaskExecution"("workspaceId");

-- CreateIndex
CREATE INDEX "PeriodicTaskExecution_periodicTaskId_idx" ON "PeriodicTaskExecution"("periodicTaskId");

-- CreateIndex
CREATE INDEX "PeriodicTaskExecution_periodicTaskId_status_idx" ON "PeriodicTaskExecution"("periodicTaskId", "status");

-- CreateIndex
CREATE INDEX "PeriodicTaskExecution_status_idx" ON "PeriodicTaskExecution"("status");
