import {
  ArrowsClockwiseIcon,
  CalendarIcon,
  CaretDownIcon,
  PaperclipIcon,
  SpinnerGapIcon,
} from '@phosphor-icons/react';
import type { inferRouterOutputs } from '@trpc/server';
import { useCallback, useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import type { AppRouter } from '@/client/lib/trpc';
import { trpc } from '@/client/lib/trpc';
import { createOptimisticWorkspaceCacheData } from '@/client/lib/workspace-cache-helpers';
import { AttachmentPreview } from '@/components/chat/attachment-preview';
import { collectAttachments } from '@/components/chat/chat-input/hooks/attachment-file-conversion';
import { usePasteDropHandler } from '@/components/chat/chat-input/hooks/use-paste-drop-handler';
import { useProjectFileMentions } from '@/components/chat/chat-input/hooks/use-project-file-mentions';
import { useSlashCommands } from '@/components/chat/chat-input/hooks/use-slash-commands';
import { FileMentionPalette } from '@/components/chat/file-mention-palette';
import { SlashCommandPalette } from '@/components/chat/slash-command-palette';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { RatchetToggleButton } from '@/components/workspace';
import type { MessageAttachment } from '@/lib/chat-protocol';
import { SUPPORTED_IMAGE_TYPES, SUPPORTED_TEXT_EXTENSIONS } from '@/lib/image-utils';
import { cn } from '@/lib/utils';
import {
  generateUniqueWorkspaceName,
  generateWorkspaceNameFromPrompt,
} from '@/shared/workspace-words';

function handleFormKeyDown(
  e: React.KeyboardEvent,
  opts: {
    delegateToSlashMenu: (key: string) => string;
    delegateToFileMentionMenu: (key: string) => string;
    isCreating: boolean;
    onCancel: () => void;
    onLaunch: () => void;
  }
) {
  if (opts.delegateToSlashMenu(e.key) === 'handled') {
    e.preventDefault();
    return;
  }
  if (opts.delegateToFileMentionMenu(e.key) === 'handled') {
    e.preventDefault();
    return;
  }
  if (!opts.isCreating) {
    if (e.key === 'Escape') {
      e.preventDefault();
      opts.onCancel();
    } else if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      opts.onLaunch();
    }
  }
}

interface InlineWorkspaceFormProps {
  projectId: string;
  existingNames?: string[];
  onCancel: () => void;
  onCreated: (workspaceId: string) => void;
}

const ATTACHMENT_ACCEPT_TYPES = [...SUPPORTED_IMAGE_TYPES, ...SUPPORTED_TEXT_EXTENSIONS].join(',');
const MAX_PROMPT_TEXTAREA_HEIGHT_PX = 240;

async function processFileInput(event: React.ChangeEvent<HTMLInputElement>) {
  const files = event.target.files;
  if (!files || files.length === 0) {
    return null;
  }
  const { attachments: newAttachments, errors } = await collectAttachments(files);
  if (errors.length > 0) {
    const formattedErrors = errors.map(({ fileName, message }) => `${fileName}: ${message}`);
    toast.error(`Could not add ${errors.length} file(s): ${formattedErrors.join('; ')}`);
  }
  event.target.value = '';
  return { newAttachments };
}

const launchButtonLabels: Record<string, string> = {
  STANDARD: 'Launch',
  AUTO_ITERATION: 'Launch (auto-iterate)',
  PERIODIC_TASK: 'Create Periodic Task',
};

type RouterOutputs = inferRouterOutputs<AppRouter>;
type KanbanWorkspace = RouterOutputs['workspace']['listWithKanbanState'][number];

interface CreateWorkspaceMutationContext {
  optimisticWorkspaceId: string;
  previousWorkspaces: KanbanWorkspace[] | undefined;
}

function createOptimisticWorkingWorkspace(params: {
  id: string;
  projectId: string;
  name: string;
  ratchetEnabled: boolean;
  mode?: 'STANDARD' | 'AUTO_ITERATION';
  createdAt?: Date;
  updatedAt?: Date;
}): KanbanWorkspace {
  const createdAt = params.createdAt ?? new Date();
  const updatedAt = params.updatedAt ?? createdAt;

  return {
    id: params.id,
    projectId: params.projectId,
    name: params.name,
    description: null,
    status: 'NEW',
    worktreePath: null,
    branchName: null,
    isAutoGeneratedBranch: false,
    creationSource: 'MANUAL',
    creationMetadata: null,
    initErrorMessage: null,
    initOutput: null,
    initStartedAt: null,
    initCompletedAt: null,
    initScriptPid: null,
    initRetryCount: 0,
    runScriptCommand: null,
    runScriptPostRunCommand: null,
    runScriptCleanupCommand: null,
    runScriptPid: null,
    runScriptPort: null,
    runScriptStartedAt: null,
    runScriptStatus: 'IDLE',
    prUrl: null,
    prDiscoveryLastCheckedAt: null,
    prDiscoveryRetryCount: 0,
    prDiscoveryNextCheckAt: null,
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    defaultSessionProvider: 'WORKSPACE_DEFAULT',
    ratchetSessionProvider: 'WORKSPACE_DEFAULT',
    createdAt,
    updatedAt,
    prNumber: null,
    prState: 'NONE',
    prReviewState: null,
    prCiStatus: 'UNKNOWN',
    prUpdatedAt: null,
    prCiFailedAt: null,
    prCiLastNotifiedAt: null,
    prReviewLastCheckedAt: null,
    prReviewLastCommentId: null,
    ratchetEnabled: params.ratchetEnabled,
    ratchetState: 'IDLE',
    ratchetLastCheckedAt: null,
    ratchetActiveSessionId: null,
    ratchetLastCiRunId: null,
    ratchetDispatchOutcome: null,
    ratchetDispatchRetryCount: 0,
    hasHadSessions: false,
    cachedKanbanColumn: 'WORKING',
    stateComputedAt: null,
    mode: params.mode ?? 'STANDARD',
    autoIterationStatus: null,
    autoIterationConfig: null,
    autoIterationProgress: null,
    autoIterationSessionId: null,
    periodicTaskId: null,
    parentWorkspaceId: null,
    agentSessions: [],
    terminalSessions: [],
    kanbanColumn: 'WORKING',
    isWorking: true,
    ratchetButtonAnimated: false,
    flowPhase: 'NO_PR',
    ciObservation: 'NOT_FETCHED',
    statusReason: {
      code: 'SETTING_UP',
      label: 'Setting up workspace',
      tone: 'working',
      needsUser: false,
    },
    isArchived: false,
    pendingRequestType: null,
  };
}

function ModeConfigPanel({
  mode,
  cadence,
  setCadence,
  scheduledTime,
  setScheduledTime,
  isCreating,
  testCommand,
  setTestCommand,
  targetDescription,
  setTargetDescription,
  maxIterations,
  setMaxIterations,
  unlimitedIterations,
  setUnlimitedIterations,
  testTimeoutSeconds,
  setTestTimeoutSeconds,
  baseBranch,
  setBaseBranch,
}: {
  mode: 'STANDARD' | 'AUTO_ITERATION' | 'PERIODIC_TASK';
  cadence: 'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  setCadence: (v: 'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY') => void;
  scheduledTime: string;
  setScheduledTime: (v: string) => void;
  isCreating: boolean;
  testCommand: string;
  setTestCommand: (v: string) => void;
  targetDescription: string;
  setTargetDescription: (v: string) => void;
  maxIterations: number;
  setMaxIterations: (v: number) => void;
  unlimitedIterations: boolean;
  setUnlimitedIterations: (v: boolean) => void;
  testTimeoutSeconds: number;
  setTestTimeoutSeconds: (v: number) => void;
  baseBranch: string;
  setBaseBranch: (v: string) => void;
}) {
  if (mode === 'PERIODIC_TASK') {
    return (
      <PeriodicTaskConfigPanel
        cadence={cadence}
        setCadence={setCadence}
        scheduledTime={scheduledTime}
        setScheduledTime={setScheduledTime}
        isCreating={isCreating}
      />
    );
  }
  if (mode === 'AUTO_ITERATION') {
    return (
      <div className="space-y-2 rounded-md border border-dashed border-primary/40 bg-primary/5 p-3">
        <div className="flex items-center gap-1.5 text-xs font-medium text-primary">
          <ArrowsClockwiseIcon className="h-3 w-3" />
          Auto-iteration config
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Test command</Label>
          <Input
            className="h-7 text-xs font-mono"
            placeholder="e.g. pnpm test"
            value={testCommand}
            onChange={(e) => setTestCommand(e.target.value)}
            disabled={isCreating}
          />
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Target description</Label>
          <Input
            className="h-7 text-xs"
            placeholder="e.g. All tests pass with no regressions"
            value={targetDescription}
            onChange={(e) => setTargetDescription(e.target.value)}
            disabled={isCreating}
          />
        </div>
        <div className="flex items-center gap-3">
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Max iterations</Label>
            <Input
              className="h-7 w-20 text-xs"
              type="number"
              min={1}
              value={unlimitedIterations ? '' : maxIterations}
              onChange={(e) => {
                if (e.target.value === '') {
                  return;
                }
                const val = Number(e.target.value);
                setMaxIterations(Number.isNaN(val) ? 25 : Math.max(1, val));
              }}
              disabled={isCreating || unlimitedIterations}
              placeholder="25"
            />
          </div>
          <label className="mt-4 flex items-center gap-1.5 text-xs text-muted-foreground">
            <Checkbox
              checked={unlimitedIterations}
              onCheckedChange={(checked) => setUnlimitedIterations(checked === true)}
              disabled={isCreating}
              className="h-3.5 w-3.5"
            />
            Unlimited
          </label>
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Test timeout (s)</Label>
            <Input
              className="h-7 w-20 text-xs"
              type="number"
              min={1}
              value={testTimeoutSeconds}
              onChange={(e) => {
                if (e.target.value === '') {
                  return;
                }
                const val = Number(e.target.value);
                setTestTimeoutSeconds(Number.isNaN(val) ? 300 : Math.max(1, val));
              }}
              disabled={isCreating}
            />
          </div>
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Base branch (optional)</Label>
          <Input
            className="h-7 text-xs font-mono"
            placeholder="defaults to project default branch"
            value={baseBranch}
            onChange={(e) => setBaseBranch(e.target.value)}
            disabled={isCreating}
          />
        </div>
      </div>
    );
  }
  return null;
}

function PeriodicTaskConfigPanel({
  cadence,
  setCadence,
  scheduledTime,
  setScheduledTime,
  isCreating,
}: {
  cadence: 'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  setCadence: (v: 'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY') => void;
  scheduledTime: string;
  setScheduledTime: (v: string) => void;
  isCreating: boolean;
}) {
  const isLongCadence = cadence === 'DAILY' || cadence === 'WEEKLY' || cadence === 'MONTHLY';
  return (
    <div className="space-y-2 rounded-md border border-dashed border-primary/40 bg-primary/5 p-3">
      <div className="flex items-center gap-1.5 text-xs font-medium text-primary">
        <CalendarIcon className="h-3 w-3" />
        Periodic task config
      </div>
      <div className="space-y-1.5">
        <Label className="text-xs text-muted-foreground">Cadence</Label>
        <Select
          value={cadence}
          onValueChange={(v) =>
            setCadence(v as 'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY')
          }
          disabled={isCreating}
        >
          <SelectTrigger className="h-7 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="EVERY_MINUTE">Every minute (testing)</SelectItem>
            <SelectItem value="EVERY_FIVE_MINUTES">Every 5 minutes (testing)</SelectItem>
            <SelectItem value="DAILY">Daily</SelectItem>
            <SelectItem value="WEEKLY">Weekly</SelectItem>
            <SelectItem value="MONTHLY">Monthly</SelectItem>
          </SelectContent>
        </Select>
      </div>
      {isLongCadence && (
        <div className="space-y-1.5">
          <Label className="text-xs text-muted-foreground">Run time (optional)</Label>
          <Input
            type="time"
            className="h-7 text-xs"
            value={scheduledTime}
            onChange={(e) => setScheduledTime(e.target.value)}
            disabled={isCreating}
          />
        </div>
      )}
      <p className="text-[10px] text-muted-foreground">
        Creates a new workspace on this schedule. The first run starts immediately.
        {isLongCadence && scheduledTime ? ' Subsequent runs will use the time above.' : ''}
      </p>
    </div>
  );
}

export function InlineWorkspaceForm({
  projectId,
  existingNames,
  onCancel,
  onCreated,
}: InlineWorkspaceFormProps) {
  const utils = trpc.useUtils();
  const { data: userSettings, isLoading: isLoadingSettings } = trpc.userSettings.get.useQuery();
  const shouldFetchExistingNames = existingNames === undefined;
  const { data: listedWorkspaces, isLoading: isLoadingWorkspaceList } =
    trpc.workspace.list.useQuery({ projectId }, { enabled: shouldFetchExistingNames });
  const availableWorkspaceNames =
    existingNames ?? listedWorkspaces?.map((workspace) => workspace.name) ?? [];

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [initialPrompt, setInitialPrompt] = useState('');
  const [attachments, setAttachments] = useState<MessageAttachment[]>([]);
  const [ratchetEnabled, setRatchetEnabled] = useState(false);
  const [provider, setProvider] = useState<'CLAUDE' | 'CODEX'>('CLAUDE');
  const [startupModePreset, setStartupModePreset] = useState<'non_interactive' | 'plan'>(
    'non_interactive'
  );
  const [mode, setMode] = useState<'STANDARD' | 'AUTO_ITERATION' | 'PERIODIC_TASK'>('STANDARD');
  const [cadence, setCadence] = useState<
    'EVERY_MINUTE' | 'EVERY_FIVE_MINUTES' | 'DAILY' | 'WEEKLY' | 'MONTHLY'
  >('DAILY');
  const [scheduledTime, setScheduledTime] = useState('');
  const [testCommand, setTestCommand] = useState('');
  const [targetDescription, setTargetDescription] = useState('');
  const [maxIterations, setMaxIterations] = useState(25);
  const [unlimitedIterations, setUnlimitedIterations] = useState(false);
  const [testTimeoutSeconds, setTestTimeoutSeconds] = useState(600);
  const [baseBranch, setBaseBranch] = useState('');

  const autoResize = useCallback(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = 'auto';
      const fullHeight = el.scrollHeight;
      const clampedHeight = Math.min(fullHeight, MAX_PROMPT_TEXTAREA_HEIGHT_PX);
      el.style.height = `${clampedHeight}px`;
      el.style.overflowY = fullHeight > MAX_PROMPT_TEXTAREA_HEIGHT_PX ? 'auto' : 'hidden';
    }
  }, []);

  const onPromptChange = useCallback(
    (value: string) => {
      setInitialPrompt(value);
      autoResize();
    },
    [autoResize]
  );

  const fileMentions = useProjectFileMentions({
    projectId,
    inputRef: textareaRef,
    onChange: onPromptChange,
  });

  const { data: slashCommandsData, isFetched: slashCommandsFetched } =
    trpc.project.listSlashCommands.useQuery({ projectId }, { staleTime: 60_000 });
  const projectCommands = slashCommandsData?.commands ?? [];

  const slashCommands = useSlashCommands({
    enabled: true,
    slashCommands: projectCommands,
    commandsLoaded: slashCommandsFetched,
    inputRef: textareaRef,
    onChange: onPromptChange,
  });

  // Initialize defaults from user settings once loaded
  useEffect(() => {
    if (!userSettings) {
      return;
    }
    setRatchetEnabled(userSettings.ratchetEnabled);
    setProvider(userSettings.defaultSessionProvider);
  }, [userSettings]);

  const createWorkspaceMutation = trpc.workspace.create.useMutation({
    onMutate: async (input): Promise<CreateWorkspaceMutationContext> => {
      const optimisticWorkspaceId = `optimistic-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      const optimisticWorkspace = createOptimisticWorkingWorkspace({
        id: optimisticWorkspaceId,
        projectId,
        name: input.type === 'MANUAL' ? input.name : 'New Workspace',
        ratchetEnabled: input.type === 'MANUAL' ? (input.ratchetEnabled ?? true) : true,
        mode: input.type === 'MANUAL' ? (input.mode ?? 'STANDARD') : 'STANDARD',
      });

      await utils.workspace.listWithKanbanState.cancel({ projectId });
      const previousWorkspaces = utils.workspace.listWithKanbanState.getData({ projectId });

      utils.workspace.listWithKanbanState.setData({ projectId }, (old) => {
        const withoutOptimistic = (old ?? []).filter(
          (workspace) => workspace.id !== optimisticWorkspaceId
        );
        return [optimisticWorkspace, ...withoutOptimistic];
      });

      return { optimisticWorkspaceId, previousWorkspaces };
    },
    onSuccess: (workspace, _input, context) => {
      const optimisticWorkspace = createOptimisticWorkingWorkspace({
        id: workspace.id,
        projectId: workspace.projectId,
        name: workspace.name,
        ratchetEnabled: workspace.ratchetEnabled,
        mode: workspace.mode ?? 'STANDARD',
        createdAt: workspace.createdAt,
        updatedAt: workspace.updatedAt,
      });

      utils.workspace.listWithKanbanState.setData({ projectId }, (old) => {
        const withoutOptimistic = (old ?? []).filter(
          (workspaceItem) =>
            workspaceItem.id !== workspace.id && workspaceItem.id !== context?.optimisticWorkspaceId
        );
        return [optimisticWorkspace, ...withoutOptimistic];
      });

      utils.workspace.get.setData({ id: workspace.id }, (old) => {
        if (old) {
          return old;
        }
        return createOptimisticWorkspaceCacheData(workspace);
      });
      utils.workspace.listWithKanbanState.invalidate({ projectId });
      utils.workspace.list.invalidate({ projectId });
      utils.workspace.getProjectSummaryState.invalidate({ projectId });
      onCreated(workspace.id);
    },
    onError: (error, _input, context) => {
      if (context) {
        utils.workspace.listWithKanbanState.setData({ projectId }, context.previousWorkspaces);
      }
      toast.error(`Failed to create workspace: ${error.message}`);
    },
  });

  const createPeriodicTaskMutation = trpc.periodicTask.create.useMutation({
    onSuccess: (task) => {
      toast.success(`Periodic task "${task.name}" created`);
      utils.periodicTask.list.invalidate({ projectId });
      onCancel();
    },
    onError: (error) => {
      toast.error(`Failed to create periodic task: ${error.message}`);
    },
  });

  const isCreating = createWorkspaceMutation.isPending || createPeriodicTaskMutation.isPending;
  const supportsWorkspaceOptions = mode !== 'PERIODIC_TASK';
  const isLaunchDisabled =
    isCreating || isLoadingSettings || (shouldFetchExistingNames && isLoadingWorkspaceList);

  const pasteDropHandler = usePasteDropHandler({
    setAttachments,
    disabled: isCreating || !supportsWorkspaceOptions,
  });

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!supportsWorkspaceOptions) {
      event.target.value = '';
      return;
    }
    const result = await processFileInput(event);
    const newFiles = result?.newAttachments ?? [];
    if (newFiles.length > 0) {
      setAttachments((prev) => [...prev, ...newFiles]);
    }
  };

  const buildAutoIterationConfig = () => ({
    testCommand: testCommand.trim(),
    targetDescription: targetDescription.trim(),
    maxIterations: unlimitedIterations ? 0 : maxIterations,
    testTimeoutSeconds,
  });

  const getAutoIterationBranchName = () => {
    const trimmed = baseBranch.trim();
    return trimmed || undefined;
  };

  const launchPeriodicTask = (trimmedPrompt: string) => {
    if (!trimmedPrompt) {
      toast.error('Periodic task requires a prompt.');
      return;
    }
    const name = generateWorkspaceNameFromPrompt(trimmedPrompt, availableWorkspaceNames);
    const isLongCadence = cadence === 'DAILY' || cadence === 'WEEKLY' || cadence === 'MONTHLY';
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    createPeriodicTaskMutation.mutate({
      projectId,
      name,
      prompt: trimmedPrompt,
      cadence,
      scheduledTime: isLongCadence && scheduledTime ? scheduledTime : null,
      timezone: isLongCadence && scheduledTime ? timezone : null,
    });
  };

  const launchWorkspace = (trimmedPrompt: string, launchMode: 'STANDARD' | 'AUTO_ITERATION') => {
    const name = trimmedPrompt
      ? generateWorkspaceNameFromPrompt(trimmedPrompt, availableWorkspaceNames)
      : generateUniqueWorkspaceName(availableWorkspaceNames);
    const isAutoIterate = launchMode === 'AUTO_ITERATION';
    createWorkspaceMutation.mutate({
      type: 'MANUAL',
      projectId,
      name,
      initialPrompt: trimmedPrompt || undefined,
      initialAttachments: attachments.length > 0 ? attachments : undefined,
      startupModePreset: startupModePreset === 'plan' ? 'plan' : undefined,
      ratchetEnabled,
      provider,
      mode: launchMode,
      autoIterationConfig: isAutoIterate ? buildAutoIterationConfig() : undefined,
      branchName: isAutoIterate ? getAutoIterationBranchName() : undefined,
    });
  };

  const handleLaunch = (launchMode: 'STANDARD' | 'AUTO_ITERATION' | 'PERIODIC_TASK' = mode) => {
    if (launchMode === 'AUTO_ITERATION' && !(testCommand.trim() && targetDescription.trim())) {
      toast.error('Auto-iteration requires a test command and target description.');
      return;
    }
    const trimmedPrompt = initialPrompt.trim();
    if (launchMode === 'PERIODIC_TASK') {
      launchPeriodicTask(trimmedPrompt);
    } else {
      launchWorkspace(trimmedPrompt, launchMode);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) =>
    handleFormKeyDown(e, {
      delegateToSlashMenu: slashCommands.delegateToSlashMenu,
      delegateToFileMentionMenu: fileMentions.delegateToFileMentionMenu,
      isCreating,
      onCancel,
      onLaunch: () => handleLaunch(mode),
    });

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    slashCommands.handleInputChange(e);
    fileMentions.detectFileMention(e.target.value);
    autoResize();
  };

  return (
    <Card className="shrink-0 border-dashed border-primary/50">
      <CardContent className="p-3 space-y-3" onKeyDown={handleKeyDown}>
        <div className="relative">
          <SlashCommandPalette
            commands={projectCommands}
            isOpen={slashCommands.slashMenuOpen}
            isLoading={!slashCommands.commandsReady}
            onClose={slashCommands.handleSlashMenuClose}
            onSelect={slashCommands.handleSlashCommandSelect}
            filter={slashCommands.slashFilter}
            anchorRef={textareaRef as React.RefObject<HTMLElement | null>}
            paletteRef={slashCommands.paletteRef}
            placement="below"
          />
          <FileMentionPalette
            files={fileMentions.files}
            isOpen={fileMentions.fileMentionMenuOpen}
            isLoading={fileMentions.filesLoading}
            onClose={fileMentions.handleFileMentionMenuClose}
            onSelect={fileMentions.handleFileMentionSelect}
            filter={fileMentions.fileMentionFilter}
            anchorRef={textareaRef as React.RefObject<HTMLElement | null>}
            paletteRef={fileMentions.paletteRef}
          />
          <Textarea
            ref={textareaRef}
            placeholder="What should the agent work on?"
            value={initialPrompt}
            onChange={handleChange}
            onPaste={pasteDropHandler.handlePaste}
            onDrop={pasteDropHandler.handleDrop}
            onDragOver={pasteDropHandler.handleDragOver}
            onDragLeave={pasteDropHandler.handleDragLeave}
            rows={3}
            className={cn(
              'resize-none text-sm',
              pasteDropHandler.isDragging && 'ring-2 ring-primary ring-inset bg-primary/5'
            )}
            autoFocus
            disabled={isCreating}
          />
        </div>
        {supportsWorkspaceOptions && attachments.length > 0 ? (
          <AttachmentPreview
            attachments={attachments}
            onRemove={(id) =>
              setAttachments((prev) => prev.filter((attachment) => attachment.id !== id))
            }
          />
        ) : null}
        <ModeConfigPanel
          mode={mode}
          cadence={cadence}
          setCadence={setCadence}
          scheduledTime={scheduledTime}
          setScheduledTime={setScheduledTime}
          isCreating={isCreating}
          testCommand={testCommand}
          setTestCommand={setTestCommand}
          targetDescription={targetDescription}
          setTargetDescription={setTargetDescription}
          maxIterations={maxIterations}
          setMaxIterations={setMaxIterations}
          unlimitedIterations={unlimitedIterations}
          setUnlimitedIterations={setUnlimitedIterations}
          testTimeoutSeconds={testTimeoutSeconds}
          setTestTimeoutSeconds={setTestTimeoutSeconds}
          baseBranch={baseBranch}
          setBaseBranch={setBaseBranch}
        />
        <div className="space-y-2">
          <div className="flex min-w-0 flex-wrap items-center gap-2">
            {supportsWorkspaceOptions ? (
              <>
                <div className="flex items-center gap-1.5">
                  <RatchetToggleButton
                    enabled={ratchetEnabled}
                    state="IDLE"
                    className="h-5 w-5"
                    onToggle={setRatchetEnabled}
                    disabled={isLoadingSettings || isCreating}
                  />
                </div>
                <Select
                  value={provider}
                  onValueChange={(v) => setProvider(v as 'CLAUDE' | 'CODEX')}
                  disabled={isLoadingSettings || isCreating}
                >
                  <SelectTrigger className="h-7 w-24 text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="CLAUDE">Claude</SelectItem>
                    <SelectItem value="CODEX">Codex</SelectItem>
                  </SelectContent>
                </Select>
                <Select
                  value={startupModePreset}
                  onValueChange={(v) => setStartupModePreset(v as 'non_interactive' | 'plan')}
                  disabled={isCreating}
                >
                  <SelectTrigger className="h-7 w-24 text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="non_interactive">Default</SelectItem>
                    <SelectItem value="plan">Plan</SelectItem>
                  </SelectContent>
                </Select>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 shrink-0 px-0"
                  aria-label="Attach files"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isCreating}
                >
                  <PaperclipIcon className="h-3.5 w-3.5" />
                </Button>
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  accept={ATTACHMENT_ACCEPT_TYPES}
                  onChange={handleFileSelect}
                  className="hidden"
                  aria-label="Attach files"
                />
              </>
            ) : null}
          </div>
          <div className="flex justify-end gap-2">
            <Button
              variant="ghost"
              size="sm"
              className="h-7 text-xs whitespace-nowrap"
              onClick={onCancel}
              disabled={isCreating}
            >
              Cancel
            </Button>
            <div className="flex">
              <Button
                size="sm"
                className={cn(
                  'h-7 text-xs whitespace-nowrap rounded-r-none',
                  mode !== 'STANDARD' && 'bg-primary/90'
                )}
                onClick={() => handleLaunch(mode)}
                disabled={isLaunchDisabled}
              >
                {isCreating ? <SpinnerGapIcon className="h-3 w-3 animate-spin mr-1" /> : null}
                {launchButtonLabels[mode]}
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    size="sm"
                    className="h-7 rounded-l-none border-l border-primary-foreground/20 px-1.5"
                    disabled={isLaunchDisabled}
                  >
                    <CaretDownIcon className="h-3 w-3" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="text-xs">
                  <DropdownMenuItem className="text-xs" onClick={() => setMode('STANDARD')}>
                    Launch as Standard Workspace
                  </DropdownMenuItem>
                  <DropdownMenuItem className="text-xs" onClick={() => setMode('AUTO_ITERATION')}>
                    <ArrowsClockwiseIcon className="mr-1.5 h-3 w-3" />
                    Launch as Auto-Iteration Workspace
                  </DropdownMenuItem>
                  <DropdownMenuItem className="text-xs" onClick={() => setMode('PERIODIC_TASK')}>
                    <CalendarIcon className="mr-1.5 h-3 w-3" />
                    Create Periodic Task
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
