import type { Meta, StoryObj } from '@storybook/react';
import type { KanbanColumn as KanbanColumnType } from '@/shared/core';
import type { WorkspaceWithKanban } from './kanban-card';
import { KANBAN_COLUMNS, KanbanColumn } from './kanban-column';

/**
 * Note: The actual KanbanBoard component cannot be fully tested in Storybook
 * because it depends on the KanbanProvider context with tRPC hooks.
 *
 * These stories demonstrate the visual layout using KanbanColumn components directly.
 * The ISSUES column requires tRPC and is not shown in these stories.
 */

// =============================================================================
// Mock Data
// =============================================================================

const baseWorkspace: WorkspaceWithKanban = {
  id: 'ws-1',
  name: 'Add user authentication',
  description: 'Implement OAuth2 login flow',
  branchName: 'feature/auth',
  isAutoGeneratedBranch: false,
  creationSource: 'MANUAL',
  creationMetadata: null,
  projectId: 'proj-1',
  worktreePath: '/path/to/worktree',
  prUrl: null,
  prDiscoveryLastCheckedAt: null,
  prDiscoveryRetryCount: 0,
  prDiscoveryNextCheckAt: null,
  prNumber: null,
  defaultSessionProvider: 'WORKSPACE_DEFAULT',
  ratchetSessionProvider: 'WORKSPACE_DEFAULT',
  prState: 'NONE',
  prReviewState: null,
  prCiStatus: 'UNKNOWN',
  prUpdatedAt: null,
  prCiFailedAt: null,
  prCiLastNotifiedAt: null,
  prReviewLastCheckedAt: null,
  prReviewLastCommentId: null,
  status: 'READY',
  createdAt: new Date(),
  updatedAt: new Date(),
  kanbanColumn: 'WORKING',
  isWorking: false,
  initErrorMessage: null,
  initOutput: null,
  initStartedAt: null,
  initCompletedAt: null,
  initScriptPid: null,
  initRetryCount: 0,
  githubIssueNumber: null,
  githubIssueUrl: null,
  linearIssueId: null,
  linearIssueIdentifier: null,
  linearIssueUrl: null,
  hasHadSessions: true,
  cachedKanbanColumn: 'WORKING',
  stateComputedAt: new Date(),
  runScriptCommand: null,
  runScriptPostRunCommand: null,
  runScriptCleanupCommand: null,
  runScriptPid: null,
  runScriptPort: null,
  runScriptStartedAt: null,
  runScriptStatus: 'IDLE',
  ratchetEnabled: true,
  ratchetState: 'IDLE',
  ratchetLastCheckedAt: null,
  ratchetButtonAnimated: false,
  flowPhase: 'NO_PR',
  ratchetActiveSessionId: null,
  ratchetLastCiRunId: null,
  ratchetDispatchOutcome: null,
  ratchetDispatchRetryCount: 0,
  isArchived: false,
  mode: 'STANDARD' as const,
  autoIterationStatus: null,
  autoIterationConfig: null,
  autoIterationProgress: null,
  autoIterationSessionId: null,
  periodicTaskId: null,
  parentWorkspaceId: null,
};

const mockWorkspaces: WorkspaceWithKanban[] = [
  {
    ...baseWorkspace,
    id: 'ws-1',
    kanbanColumn: 'WORKING',
    name: 'Add authentication',
    isWorking: true,
  },
  { ...baseWorkspace, id: 'ws-2', kanbanColumn: 'WORKING', name: 'Fix login bug', status: 'NEW' },
  {
    ...baseWorkspace,
    id: 'ws-3',
    kanbanColumn: 'WAITING',
    name: 'Update dependencies',
    prNumber: 42,
    prUrl: '#',
    prState: 'OPEN',
  },
  {
    ...baseWorkspace,
    id: 'ws-4',
    kanbanColumn: 'WAITING',
    name: 'Add dark mode',
    prNumber: 43,
    prUrl: '#',
    prState: 'APPROVED',
  },
  {
    ...baseWorkspace,
    id: 'ws-5',
    kanbanColumn: 'DONE',
    name: 'Fix typo',
    prNumber: 40,
    prUrl: '#',
    prState: 'MERGED',
  },
];

// Only workspace columns (not ISSUES which requires tRPC)
const WORKSPACE_COLUMNS = KANBAN_COLUMNS.filter((col) => col.id !== 'ISSUES');

function groupByColumn(workspaces: WorkspaceWithKanban[]) {
  const grouped: Record<KanbanColumnType, WorkspaceWithKanban[]> = {
    WORKING: [],
    WAITING: [],
    DONE: [],
  };
  for (const ws of workspaces) {
    const col = ws.kanbanColumn as KanbanColumnType;
    if (col in grouped) {
      grouped[col].push(ws);
    }
  }
  return grouped;
}

// =============================================================================
// Mock Board Component for Storybook
// =============================================================================

function MockKanbanBoard({ workspaces }: { workspaces: WorkspaceWithKanban[] }) {
  const grouped = groupByColumn(workspaces);
  return (
    <div className="flex gap-4 overflow-x-auto pb-4">
      {WORKSPACE_COLUMNS.map((column) => (
        <KanbanColumn
          key={column.id}
          column={column}
          workspaces={grouped[column.id as KanbanColumnType] ?? []}
          projectSlug="demo"
        />
      ))}
    </div>
  );
}

// =============================================================================
// Story Meta
// =============================================================================

const meta = {
  title: 'Kanban/KanbanBoard',
  component: MockKanbanBoard,
  parameters: {
    layout: 'fullscreen',
    nextjs: {
      appDirectory: true,
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof MockKanbanBoard>;

export default meta;
type Story = StoryObj<typeof meta>;

// =============================================================================
// Stories
// =============================================================================

export const WithData: Story = {
  args: {
    workspaces: mockWorkspaces,
  },
};

export const Empty: Story = {
  args: {
    workspaces: [],
  },
};

export const FewWorkspaces: Story = {
  args: {
    workspaces: mockWorkspaces.slice(0, 2),
  },
};

export const AllWorking: Story = {
  args: {
    workspaces: [
      { ...baseWorkspace, id: 'ws-1', name: 'Task 1', kanbanColumn: 'WORKING', isWorking: true },
      { ...baseWorkspace, id: 'ws-2', name: 'Task 2', kanbanColumn: 'WORKING', isWorking: true },
      { ...baseWorkspace, id: 'ws-3', name: 'Task 3', kanbanColumn: 'WORKING', status: 'NEW' },
      {
        ...baseWorkspace,
        id: 'ws-4',
        name: 'Task 4',
        kanbanColumn: 'WORKING',
        status: 'PROVISIONING',
      },
    ],
  },
};

export const WithArchivedWorkspaces: Story = {
  args: {
    workspaces: [
      ...mockWorkspaces,
      {
        ...baseWorkspace,
        id: 'ws-archived-1',
        name: 'Archived task',
        kanbanColumn: 'WAITING',
        status: 'ARCHIVED',
        isArchived: true,
      },
      {
        ...baseWorkspace,
        id: 'ws-archived-2',
        name: 'Another archived',
        kanbanColumn: 'DONE',
        status: 'ARCHIVED',
        isArchived: true,
        prState: 'MERGED',
      },
    ],
  },
};
