import type { Meta, StoryObj } from '@storybook/react';
import type { WorkspaceWithKanban } from './kanban-card';
import { KANBAN_COLUMNS, KanbanColumn } from './kanban-column';

const meta = {
  title: 'Kanban/KanbanColumn',
  component: KanbanColumn,
  parameters: {
    layout: 'centered',
    nextjs: {
      appDirectory: true,
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof KanbanColumn>;

export default meta;
type Story = StoryObj<typeof meta>;

const baseWorkspace: WorkspaceWithKanban = {
  id: 'ws-1',
  name: 'Add user authentication',
  description: 'Implement OAuth2 login flow',
  branchName: 'feature/auth',
  isAutoGeneratedBranch: false,
  creationSource: 'MANUAL',
  creationMetadata: null,
  projectId: 'proj-1',
  worktreePath: '/path/to/worktree',
  prUrl: null,
  prDiscoveryLastCheckedAt: null,
  prDiscoveryRetryCount: 0,
  prDiscoveryNextCheckAt: null,
  prNumber: null,
  defaultSessionProvider: 'WORKSPACE_DEFAULT',
  ratchetSessionProvider: 'WORKSPACE_DEFAULT',
  prState: 'NONE',
  prReviewState: null,
  prCiStatus: 'UNKNOWN',
  prUpdatedAt: null,
  prCiFailedAt: null,
  prCiLastNotifiedAt: null,
  prReviewLastCheckedAt: null,
  prReviewLastCommentId: null,
  status: 'READY',
  createdAt: new Date(),
  updatedAt: new Date(),
  kanbanColumn: 'WORKING',
  isWorking: false,
  initErrorMessage: null,
  initOutput: null,
  initStartedAt: null,
  initCompletedAt: null,
  initScriptPid: null,
  initRetryCount: 0,
  githubIssueNumber: null,
  githubIssueUrl: null,
  linearIssueId: null,
  linearIssueIdentifier: null,
  linearIssueUrl: null,
  hasHadSessions: true,
  cachedKanbanColumn: 'WORKING',
  stateComputedAt: new Date(),
  runScriptCommand: null,
  runScriptPostRunCommand: null,
  runScriptCleanupCommand: null,
  runScriptPid: null,
  runScriptPort: null,
  runScriptStartedAt: null,
  runScriptStatus: 'IDLE',
  ratchetEnabled: true,
  ratchetState: 'IDLE',
  ratchetLastCheckedAt: null,
  ratchetButtonAnimated: false,
  flowPhase: 'NO_PR',
  ratchetActiveSessionId: null,
  ratchetLastCiRunId: null,
  ratchetDispatchOutcome: null,
  ratchetDispatchRetryCount: 0,
  isArchived: false,
  mode: 'STANDARD' as const,
  autoIterationStatus: null,
  autoIterationConfig: null,
  autoIterationProgress: null,
  autoIterationSessionId: null,
  periodicTaskId: null,
  parentWorkspaceId: null,
};

const mockWorkspaces: WorkspaceWithKanban[] = [
  baseWorkspace,
  {
    ...baseWorkspace,
    id: 'ws-2',
    name: 'Fix login validation',
    branchName: 'fix/login',
    prUrl: 'https://github.com/example/repo/pull/42',
    prNumber: 42,
    prState: 'OPEN',
    kanbanColumn: 'WAITING',
  },
  {
    ...baseWorkspace,
    id: 'ws-3',
    name: 'Update dependencies',
    branchName: 'chore/deps',
    isWorking: true,
    kanbanColumn: 'WORKING',
  },
];

// Define columns directly to avoid non-null assertions
const workingColumn = {
  id: 'WORKING' as const,
  label: 'Working',
  description: 'Agent is working',
};
const waitingColumn = {
  id: 'WAITING' as const,
  label: 'Waiting',
  description: 'Waiting for input',
};
const doneColumn = { id: 'DONE' as const, label: 'Done', description: 'PR merged' };

export const Empty: Story = {
  args: {
    column: waitingColumn,
    workspaces: [],
    projectSlug: 'my-project',
  },
};

export const SingleWorkspace: Story = {
  args: {
    column: workingColumn,
    workspaces: [baseWorkspace],
    projectSlug: 'my-project',
  },
};

export const MultipleWorkspaces: Story = {
  args: {
    column: workingColumn,
    workspaces: mockWorkspaces.filter((w) => w.kanbanColumn === 'WORKING'),
    projectSlug: 'my-project',
  },
};

export const WaitingColumn: Story = {
  args: {
    column: waitingColumn,
    workspaces: [
      {
        ...baseWorkspace,
        id: 'ws-wait-1',
        name: 'Feature A',
        prUrl: 'https://github.com/example/repo/pull/100',
        prNumber: 100,
        prState: 'OPEN',
        prCiStatus: 'PENDING',
        kanbanColumn: 'WAITING',
      },
      {
        ...baseWorkspace,
        id: 'ws-wait-2',
        name: 'Feature B',
        prUrl: 'https://github.com/example/repo/pull/101',
        prNumber: 101,
        prState: 'APPROVED',
        prCiStatus: 'SUCCESS',
        kanbanColumn: 'WAITING',
      },
    ],
    projectSlug: 'my-project',
  },
};

export const DoneColumn: Story = {
  args: {
    column: doneColumn,
    workspaces: [
      {
        ...baseWorkspace,
        id: 'ws-done-1',
        name: 'Completed feature',
        prUrl: 'https://github.com/example/repo/pull/99',
        prNumber: 99,
        prState: 'MERGED',
        prCiStatus: 'SUCCESS',
        kanbanColumn: 'DONE',
      },
    ],
    projectSlug: 'my-project',
  },
};

// Workspace columns only (ISSUES requires tRPC)
const WORKSPACE_COLUMNS = KANBAN_COLUMNS.filter((col) => col.id !== 'ISSUES');

export const AllColumns: Story = {
  decorators: [
    () => (
      <div className="flex gap-4 overflow-x-auto p-4">
        {WORKSPACE_COLUMNS.map((column) => (
          <KanbanColumn
            key={column.id}
            column={column}
            workspaces={
              column.id === 'WORKING'
                ? mockWorkspaces.filter((w) => w.kanbanColumn === 'WORKING')
                : column.id === 'WAITING'
                  ? mockWorkspaces.filter((w) => w.kanbanColumn === 'WAITING')
                  : []
            }
            projectSlug="demo"
          />
        ))}
      </div>
    ),
  ],
  args: {
    column: workingColumn,
    workspaces: [],
    projectSlug: 'demo',
  },
};
