import type { Meta, StoryObj } from '@storybook/react';
import type { WorkspaceWithKanban } from './kanban-card';
import { KanbanCard } from './kanban-card';

const meta = {
  title: 'Kanban/KanbanCard',
  component: KanbanCard,
  parameters: {
    layout: 'centered',
    nextjs: {
      appDirectory: true,
    },
  },
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <div className="w-[380px]">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof KanbanCard>;

export default meta;
type Story = StoryObj<typeof meta>;

const baseWorkspace: WorkspaceWithKanban = {
  id: 'ws-1',
  name: 'Add user authentication',
  description: 'Implement OAuth2 login flow',
  branchName: 'feature/auth',
  isAutoGeneratedBranch: false,
  creationSource: 'MANUAL',
  creationMetadata: null,
  projectId: 'proj-1',
  worktreePath: '/path/to/worktree',
  prUrl: null,
  prDiscoveryLastCheckedAt: null,
  prDiscoveryRetryCount: 0,
  prDiscoveryNextCheckAt: null,
  prNumber: null,
  defaultSessionProvider: 'WORKSPACE_DEFAULT',
  ratchetSessionProvider: 'WORKSPACE_DEFAULT',
  prState: 'NONE',
  prReviewState: null,
  prCiStatus: 'UNKNOWN',
  prUpdatedAt: null,
  prCiFailedAt: null,
  prCiLastNotifiedAt: null,
  prReviewLastCheckedAt: null,
  prReviewLastCommentId: null,
  status: 'READY',
  createdAt: new Date(),
  updatedAt: new Date(),
  kanbanColumn: 'WORKING',
  isWorking: false,
  initErrorMessage: null,
  initOutput: null,
  initStartedAt: null,
  initCompletedAt: null,
  initScriptPid: null,
  initRetryCount: 0,
  githubIssueNumber: null,
  githubIssueUrl: null,
  linearIssueId: null,
  linearIssueIdentifier: null,
  linearIssueUrl: null,
  hasHadSessions: true,
  cachedKanbanColumn: 'WORKING',
  stateComputedAt: new Date(),
  runScriptCommand: null,
  runScriptPostRunCommand: null,
  runScriptCleanupCommand: null,
  runScriptPid: null,
  runScriptPort: null,
  runScriptStartedAt: null,
  runScriptStatus: 'IDLE',
  ratchetEnabled: true,
  ratchetState: 'IDLE',
  ratchetLastCheckedAt: null,
  ratchetButtonAnimated: false,
  flowPhase: 'NO_PR',
  ratchetActiveSessionId: null,
  ratchetLastCiRunId: null,
  ratchetDispatchOutcome: null,
  ratchetDispatchRetryCount: 0,
  isArchived: false,
  mode: 'STANDARD' as const,
  autoIterationStatus: null,
  autoIterationConfig: null,
  autoIterationProgress: null,
  autoIterationSessionId: null,
  periodicTaskId: null,
  parentWorkspaceId: null,
};

export const NoPR: Story = {
  args: {
    workspace: baseWorkspace,
    projectSlug: 'my-project',
  },
};

export const DraftPR: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      prUrl: 'https://github.com/example/repo/pull/42',
      prNumber: 42,
      prState: 'DRAFT',
    },
    projectSlug: 'my-project',
  },
};

export const OpenPR: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      prUrl: 'https://github.com/example/repo/pull/43',
      prNumber: 43,
      prState: 'OPEN',
      prCiStatus: 'PENDING',
    },
    projectSlug: 'my-project',
  },
};

export const ChangesRequested: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Fix login validation',
      prUrl: 'https://github.com/example/repo/pull/44',
      prNumber: 44,
      prState: 'CHANGES_REQUESTED',
      prCiStatus: 'SUCCESS',
    },
    projectSlug: 'my-project',
  },
};

export const Approved: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Add password reset flow',
      prUrl: 'https://github.com/example/repo/pull/45',
      prNumber: 45,
      prState: 'APPROVED',
      prCiStatus: 'SUCCESS',
    },
    projectSlug: 'my-project',
  },
};

export const Merged: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Implement MFA support',
      prUrl: 'https://github.com/example/repo/pull/46',
      prNumber: 46,
      prState: 'MERGED',
      kanbanColumn: 'DONE',
    },
    projectSlug: 'my-project',
  },
};

export const Closed: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Deprecated feature branch',
      prUrl: 'https://github.com/example/repo/pull/47',
      prNumber: 47,
      prState: 'CLOSED',
      kanbanColumn: 'WAITING',
    },
    projectSlug: 'my-project',
  },
};

export const Archived: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Archived workspace',
      prUrl: 'https://github.com/example/repo/pull/50',
      prNumber: 50,
      prState: 'MERGED',
      status: 'ARCHIVED',
      kanbanColumn: 'DONE',
      isArchived: true,
    },
    projectSlug: 'my-project',
  },
};

export const ArchivedInWaiting: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Archived with open PR',
      prUrl: 'https://github.com/example/repo/pull/51',
      prNumber: 51,
      prState: 'OPEN',
      status: 'ARCHIVED',
      kanbanColumn: 'WAITING',
      isArchived: true,
    },
    projectSlug: 'my-project',
  },
};

export const Working: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Active coding session',
      isWorking: true,
      prState: 'OPEN',
      prUrl: 'https://github.com/example/repo/pull/48',
      prNumber: 48,
    },
    projectSlug: 'my-project',
  },
};

export const Provisioning: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'New workspace',
      status: 'PROVISIONING',
      branchName: null,
    },
    projectSlug: 'my-project',
  },
};

export const RatchetOnProcessing: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Ratchet fixing CI',
      prState: 'OPEN',
      prUrl: 'https://github.com/example/repo/pull/50',
      prNumber: 50,
      prCiStatus: 'FAILURE',
      ratchetState: 'CI_FAILED',
    },
    projectSlug: 'my-project',
  },
};

export const RatchetReviewPending: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Ratchet addressing reviews',
      prState: 'CHANGES_REQUESTED',
      prUrl: 'https://github.com/example/repo/pull/51',
      prNumber: 51,
      prCiStatus: 'SUCCESS',
      ratchetState: 'REVIEW_PENDING',
    },
    projectSlug: 'my-project',
  },
};

export const RatchetReady: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Ratchet ready to merge',
      prState: 'APPROVED',
      prUrl: 'https://github.com/example/repo/pull/52',
      prNumber: 52,
      prCiStatus: 'SUCCESS',
      ratchetState: 'READY',
    },
    projectSlug: 'my-project',
  },
};

export const RatchetOff: Story = {
  args: {
    workspace: {
      ...baseWorkspace,
      name: 'Ratchet disabled',
      ratchetEnabled: false,
      ratchetState: 'CI_FAILED',
      prState: 'OPEN',
      prUrl: 'https://github.com/example/repo/pull/53',
      prNumber: 53,
    },
    projectSlug: 'my-project',
  },
};

export const AllPRStates: Story = {
  decorators: [
    () => (
      <div className="flex flex-wrap gap-4">
        <div className="w-[380px]">
          <KanbanCard
            workspace={{ ...baseWorkspace, prState: 'DRAFT', prNumber: 1, prUrl: '#' }}
            projectSlug="demo"
          />
        </div>
        <div className="w-[380px]">
          <KanbanCard
            workspace={{ ...baseWorkspace, prState: 'OPEN', prNumber: 2, prUrl: '#' }}
            projectSlug="demo"
          />
        </div>
        <div className="w-[380px]">
          <KanbanCard
            workspace={{
              ...baseWorkspace,
              prState: 'CHANGES_REQUESTED',
              prNumber: 3,
              prUrl: '#',
            }}
            projectSlug="demo"
          />
        </div>
        <div className="w-[380px]">
          <KanbanCard
            workspace={{ ...baseWorkspace, prState: 'APPROVED', prNumber: 4, prUrl: '#' }}
            projectSlug="demo"
          />
        </div>
        <div className="w-[380px]">
          <KanbanCard
            workspace={{ ...baseWorkspace, prState: 'MERGED', prNumber: 5, prUrl: '#' }}
            projectSlug="demo"
          />
        </div>
        <div className="w-[380px]">
          <KanbanCard
            workspace={{ ...baseWorkspace, prState: 'CLOSED', prNumber: 6, prUrl: '#' }}
            projectSlug="demo"
          />
        </div>
      </div>
    ),
  ],
  args: {
    workspace: baseWorkspace,
    projectSlug: 'demo',
  },
};
