import { describe, expect, it, vi } from 'vitest';

vi.mock('@/backend/prompts/branch-rename', () => ({
  buildBranchRenameInstruction: vi.fn(),
}));

vi.mock('@/backend/prompts/workflows', () => ({
  getWorkflowContent: vi.fn(),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

import { buildBranchRenameInstruction } from '@/backend/prompts/branch-rename';
import { getWorkflowContent } from '@/backend/prompts/workflows';
import { SessionPromptBuilder } from './session.prompt-builder';

describe('SessionPromptBuilder', () => {
  describe('shouldInjectBranchRename', () => {
    const builder = new SessionPromptBuilder();

    it('returns true when branch is auto-generated and no sessions have run', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: 'auto-branch',
          isAutoGeneratedBranch: true,
          hasHadSessions: false,
        })
      ).toBe(true);
    });

    it('returns false when workspace has already had sessions', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: 'auto-branch',
          isAutoGeneratedBranch: true,
          hasHadSessions: true,
        })
      ).toBe(false);
    });

    it('returns false when branch is not auto-generated', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: 'feature/my-branch',
          isAutoGeneratedBranch: false,
          hasHadSessions: false,
        })
      ).toBe(false);
    });

    it('returns false when branch name is missing', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: null,
          isAutoGeneratedBranch: true,
          hasHadSessions: false,
        })
      ).toBe(false);
    });

    it('returns false when isAutoGeneratedBranch is undefined', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: 'some-branch',
          isAutoGeneratedBranch: undefined,
          hasHadSessions: false,
        })
      ).toBe(false);
    });

    it('returns false when hasHadSessions is undefined (safer default for older workspaces)', () => {
      expect(
        builder.shouldInjectBranchRename({
          branchName: 'auto-branch',
          isAutoGeneratedBranch: true,
          hasHadSessions: undefined,
        })
      ).toBe(false);
    });
  });

  it('injects branch rename instruction for auto-generated branches on first session', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');
    vi.mocked(buildBranchRenameInstruction).mockReturnValue('rename');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'ci-fix',
      workspace: {
        branchName: 'auto-branch',
        isAutoGeneratedBranch: true,
        hasHadSessions: false,
        name: 'Workspace A',
        description: 'desc',
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('renameworkflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(true);
  });

  it('uses workflow prompt without branch rename when branch is not auto-generated', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'ci-fix',
      workspace: {
        branchName: 'feature/real',
        isAutoGeneratedBranch: false,
        hasHadSessions: false,
        name: 'Workspace B',
        description: null,
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('workflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(false);
  });

  it('returns undefined system prompt when workflow prompt is missing', () => {
    vi.mocked(getWorkflowContent).mockReturnValue(null);

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'missing',
      workspace: {
        branchName: null,
        isAutoGeneratedBranch: false,
        name: 'Workspace C',
        description: null,
      },
      project: null,
    });

    expect(result.systemPrompt).toBeUndefined();
    expect(result.workflowPrompt).toBeUndefined();
    expect(result.injectedBranchRename).toBe(false);
  });

  it('does not inject branch rename when isAutoGeneratedBranch is undefined', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'ci-fix',
      workspace: {
        branchName: 'some-branch',
        // isAutoGeneratedBranch not set (undefined)
        name: 'Workspace D',
        description: null,
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('workflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(false);
  });

  it('does not inject branch rename when workspace has already had sessions', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'ci-fix',
      workspace: {
        branchName: 'auto-branch',
        isAutoGeneratedBranch: true,
        hasHadSessions: true,
        name: 'Workspace F',
        description: 'desc',
      },
      project: { githubOwner: 'owner' },
    });

    expect(result.systemPrompt).toBe('workflow');
    expect(result.workflowPrompt).toBe('workflow');
    expect(result.injectedBranchRename).toBe(false);
  });

  it('uses default Claude prompt for regular user sessions', () => {
    vi.mocked(getWorkflowContent).mockReturnValue('workflow');

    const builder = new SessionPromptBuilder();
    const result = builder.buildSystemPrompt({
      workflow: 'followup',
      workspace: {
        branchName: null,
        isAutoGeneratedBranch: false,
        name: 'Workspace E',
        description: null,
      },
      project: null,
    });

    expect(result.systemPrompt).toBeUndefined();
    expect(result.workflowPrompt).toBeUndefined();
    expect(result.injectedBranchRename).toBe(false);
  });

  describe('claudeMdContent', () => {
    it('appends CLAUDE.md content to the system prompt when present', () => {
      vi.mocked(getWorkflowContent).mockReturnValue('workflow');

      const builder = new SessionPromptBuilder();
      const result = builder.buildSystemPrompt({
        workflow: 'ci-fix',
        workspace: {
          branchName: 'main',
          isAutoGeneratedBranch: false,
          name: 'Workspace',
          description: null,
        },
        project: null,
        claudeMdContent: '# Repo Instructions',
      });

      expect(result.systemPrompt).toBe('workflow\n\n# Repo Instructions');
    });

    it('uses CLAUDE.md as the system prompt when no workflow prompt exists', () => {
      vi.mocked(getWorkflowContent).mockReturnValue(null);

      const builder = new SessionPromptBuilder();
      const result = builder.buildSystemPrompt({
        workflow: 'followup',
        workspace: {
          branchName: null,
          isAutoGeneratedBranch: false,
          name: 'Workspace',
          description: null,
        },
        project: null,
        claudeMdContent: '# Repo Instructions',
      });

      expect(result.systemPrompt).toBe('\n\n# Repo Instructions');
      expect(result.workflowPrompt).toBeUndefined();
    });

    it('does not modify system prompt when claudeMdContent is null', () => {
      vi.mocked(getWorkflowContent).mockReturnValue('workflow');

      const builder = new SessionPromptBuilder();
      const result = builder.buildSystemPrompt({
        workflow: 'ci-fix',
        workspace: {
          branchName: 'main',
          isAutoGeneratedBranch: false,
          name: 'Workspace',
          description: null,
        },
        project: null,
        claudeMdContent: null,
      });

      expect(result.systemPrompt).toBe('workflow');
    });

    it('appends CLAUDE.md after branch rename instruction', () => {
      vi.mocked(getWorkflowContent).mockReturnValue('workflow');
      vi.mocked(buildBranchRenameInstruction).mockReturnValue('rename');

      const builder = new SessionPromptBuilder();
      const result = builder.buildSystemPrompt({
        workflow: 'ci-fix',
        workspace: {
          branchName: 'auto-branch',
          isAutoGeneratedBranch: true,
          hasHadSessions: false,
          name: 'Workspace',
          description: null,
        },
        project: { githubOwner: 'owner' },
        claudeMdContent: '# Repo Instructions',
      });

      expect(result.systemPrompt).toBe('renameworkflow\n\n# Repo Instructions');
      expect(result.injectedBranchRename).toBe(true);
    });
  });
});
