import { buildBranchRenameInstruction } from '@/backend/prompts/branch-rename';
import { getWorkflowContent } from '@/backend/prompts/workflows';

export type BuildPromptInput = {
  workflow: string;
  workspace: {
    branchName?: string | null;
    isAutoGeneratedBranch?: boolean;
    hasHadSessions?: boolean;
    name: string;
    description?: string | null;
    runScriptPort?: number | null;
  };
  project?: { githubOwner?: string | null } | null;
  claudeMdContent?: string | null;
};

export type BuildPromptResult = {
  workflowPrompt: string | undefined;
  systemPrompt: string | undefined;
  injectedBranchRename: boolean;
};

export class SessionPromptBuilder {
  /**
   * Workflow prompts reserved for automated helper sessions.
   * User-created chat sessions should use Claude's default system prompt.
   */
  private static readonly PROMPTED_WORKFLOWS = new Set(['ci-fix', 'pr-review-fix', 'ratchet']);

  /**
   * Check if branch rename should be injected based on the stored flag.
   * Uses the isAutoGeneratedBranch flag rather than pattern matching,
   * so we don't break if workspace words are changed in the future.
   *
   * Only injects branch rename for the first session - additional sessions
   * should not rename the branch again.
   *
   * Note: If hasHadSessions is undefined, we treat it as true (safer default)
   * to avoid repeatedly injecting rename instructions for older workspaces.
   */
  shouldInjectBranchRename(workspace: {
    branchName?: string | null;
    isAutoGeneratedBranch?: boolean;
    hasHadSessions?: boolean;
  }): boolean {
    return (
      !!workspace.branchName &&
      !!workspace.isAutoGeneratedBranch &&
      workspace.hasHadSessions === false
    );
  }

  buildSystemPrompt({
    workflow,
    workspace,
    project,
    claudeMdContent,
  }: BuildPromptInput): BuildPromptResult {
    const workflowPrompt = SessionPromptBuilder.PROMPTED_WORKFLOWS.has(workflow)
      ? (getWorkflowContent(workflow) ?? undefined)
      : undefined;
    let systemPrompt = workflowPrompt;
    let injectedBranchRename = false;

    if (this.shouldInjectBranchRename(workspace)) {
      const branchRenameInstruction = buildBranchRenameInstruction({
        branchPrefix: project?.githubOwner ?? '',
        workspaceName: workspace.name,
        workspaceDescription: workspace.description ?? undefined,
      });
      systemPrompt = branchRenameInstruction + (workflowPrompt ?? '');
      injectedBranchRename = true;
    }

    if (claudeMdContent) {
      systemPrompt = `${systemPrompt ?? ''}\n\n${claudeMdContent}`;
    }

    if (workspace.runScriptPort) {
      const devServerInfo = `\n\n## Dev Server\nA development server is running at http://localhost:${workspace.runScriptPort}. You can use Playwright MCP tools (browser_navigate, browser_screenshot) to capture screenshots of UI changes.\n`;
      systemPrompt = (systemPrompt ?? '') + devServerInfo;
    }

    return { workflowPrompt, systemPrompt, injectedBranchRename };
  }
}

export const sessionPromptBuilder = new SessionPromptBuilder();
