/**
 * Shared schema for export/import data validation.
 *
 * This schema is used by both the backend (for export/import operations)
 * and the frontend (for pre-validation of import files).
 *
 * Note: Uses string enums instead of Prisma enums to avoid pulling
 * Prisma client into the browser bundle.
 */

import { z } from 'zod';
import {
  CIStatus as CoreCIStatus,
  IssueProvider as CoreIssueProvider,
  KanbanColumn as CoreKanbanColumn,
  PRState as CorePRState,
  RatchetReviewTriggerMode as CoreRatchetReviewTriggerMode,
  RatchetState as CoreRatchetState,
  RunScriptStatus as CoreRunScriptStatus,
  SessionPermissionPreset as CoreSessionPermissionPreset,
  SessionProvider as CoreSessionProvider,
  SessionStatus as CoreSessionStatus,
  WorkspaceCreationSource as CoreWorkspaceCreationSource,
  WorkspaceMode as CoreWorkspaceMode,
  WorkspaceProviderSelection as CoreWorkspaceProviderSelection,
  WorkspaceStatus as CoreWorkspaceStatus,
} from '@/shared/core';
import { autoIterationConfigSchema } from './auto-iteration.schema';

function enumValues<const T extends Record<string, string>>(enumObject: T) {
  return Object.values(enumObject) as [T[keyof T], ...T[keyof T][]];
}

// Use core as the single enum source-of-truth (browser-safe, no Prisma dependency).
const WorkspaceStatus = z.enum(enumValues(CoreWorkspaceStatus));
const WorkspaceCreationSource = z.enum(enumValues(CoreWorkspaceCreationSource));
const IssueProvider = z.enum(enumValues(CoreIssueProvider));
const RunScriptStatus = z.enum(enumValues(CoreRunScriptStatus));
const WorkspaceMode = z.enum(enumValues(CoreWorkspaceMode));
const PRState = z.enum(enumValues(CorePRState));
const CIStatus = z.enum(enumValues(CoreCIStatus));
const KanbanColumn = z.enum(enumValues(CoreKanbanColumn));
const RatchetState = z.enum(enumValues(CoreRatchetState));
const RatchetReviewTriggerMode = z.enum(enumValues(CoreRatchetReviewTriggerMode));
const SessionStatus = z.enum(enumValues(CoreSessionStatus));
const SessionProvider = z.enum(enumValues(CoreSessionProvider));
const SessionPermissionPreset = z.enum(enumValues(CoreSessionPermissionPreset));
const WorkspaceProviderSelection = z.enum(enumValues(CoreWorkspaceProviderSelection));

const exportedProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  repoPath: z.string(),
  worktreeBasePath: z.string(),
  defaultBranch: z.string(),
  githubOwner: z.string().nullable(),
  githubRepo: z.string().nullable(),
  issueProvider: IssueProvider,
  issueTrackerConfig: z.unknown().nullable(),
  isArchived: z.boolean(),
  startupScriptCommand: z.string().nullable(),
  startupScriptPath: z.string().nullable(),
  startupScriptTimeout: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedWorkspaceSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  status: WorkspaceStatus,
  worktreePath: z.string().nullable(),
  branchName: z.string().nullable(),
  isAutoGeneratedBranch: z.boolean(),
  creationSource: WorkspaceCreationSource,
  creationMetadata: z.unknown().nullable(),
  initErrorMessage: z.string().nullable(),
  initOutput: z.string().nullable(),
  initStartedAt: z.string().nullable(),
  initCompletedAt: z.string().nullable(),
  initRetryCount: z.number(),
  runScriptCommand: z.string().nullable(),
  runScriptCleanupCommand: z.string().nullable(),
  runScriptPid: z.number().nullable(),
  runScriptPort: z.number().nullable(),
  runScriptStartedAt: z.string().nullable(),
  runScriptStatus: RunScriptStatus,
  mode: WorkspaceMode.optional().default('STANDARD'),
  autoIterationConfig: autoIterationConfigSchema.nullable().optional().default(null),
  prUrl: z.string().nullable(),
  githubIssueNumber: z.number().nullable(),
  githubIssueUrl: z.string().nullable(),
  linearIssueId: z.string().nullable(),
  linearIssueIdentifier: z.string().nullable(),
  linearIssueUrl: z.string().nullable(),
  defaultSessionProvider: WorkspaceProviderSelection,
  ratchetSessionProvider: WorkspaceProviderSelection,
  prNumber: z.number().nullable(),
  prState: PRState,
  prReviewState: z.string().nullable(),
  prCiStatus: CIStatus,
  prUpdatedAt: z.string().nullable(),
  prCiFailedAt: z.string().nullable(),
  prCiLastNotifiedAt: z.string().nullable(),
  prReviewLastCheckedAt: z.string().nullable(),
  prReviewLastCommentId: z.string().nullable(),
  ratchetEnabled: z.boolean(),
  ratchetState: RatchetState,
  ratchetLastCheckedAt: z.string().nullable(),
  ratchetActiveSessionId: z.string().nullable(),
  ratchetLastCiRunId: z.string().nullable(),
  hasHadSessions: z.boolean(),
  cachedKanbanColumn: KanbanColumn,
  stateComputedAt: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedAgentSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  workflow: z.string(),
  model: z.string(),
  status: SessionStatus,
  provider: SessionProvider,
  providerSessionId: z.string().nullable(),
  providerProjectPath: z.string().nullable(),
  providerProcessPid: z.number().nullable(),
  providerMetadata: z.unknown().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedTerminalSessionSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string().nullable(),
  status: SessionStatus,
  pid: z.number().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const exportedUserSettingsSchema = z.object({
  preferredIde: z.string(),
  customIdeCommand: z.string().nullable(),
  playSoundOnComplete: z.boolean(),
  notificationSoundPath: z.string().nullable(),
  ratchetEnabled: z.boolean(),
  ratchetReplyToPrComments: z.boolean().optional().default(true),
  ratchetReviewTriggerMode: RatchetReviewTriggerMode.optional().default('CHANGES_REQUESTED'),
  defaultSessionProvider: SessionProvider,
  defaultClaudeModel: z.string().optional().default('sonnet'),
  defaultCodexModel: z.string().optional().default('default'),
  defaultClaudeReasoningEffort: z.string().nullable().optional().default(null),
  defaultCodexReasoningEffort: z.string().nullable().optional().default(null),
  defaultWorkspacePermissions: SessionPermissionPreset.optional().default('STRICT'),
  ratchetPermissions: SessionPermissionPreset.optional().default('YOLO'),
});

export const exportDataSchema = z.object({
  meta: z.object({
    exportedAt: z.string(),
    version: z.string(),
    schemaVersion: z.literal(4),
  }),
  data: z.object({
    projects: z.array(exportedProjectSchema),
    workspaces: z.array(exportedWorkspaceSchema),
    agentSessions: z.array(exportedAgentSessionSchema),
    terminalSessions: z.array(exportedTerminalSessionSchema),
    userSettings: exportedUserSettingsSchema.nullable(),
  }),
});

export {
  exportedProjectSchema,
  exportedWorkspaceSchema,
  exportedAgentSessionSchema,
  exportedTerminalSessionSchema,
  exportedUserSettingsSchema,
};

export type ExportData = z.infer<typeof exportDataSchema>;
