/**
 * Tests for export-data schema enum synchronization with Prisma.
 *
 * These tests ensure that the Zod enum values stay in sync with Prisma-generated enums.
 * If Prisma schema enums are modified, these tests will fail, prompting updates to the
 * shared schema to prevent backup import failures.
 */

import { RatchetReviewTriggerMode as PrismaRatchetReviewTriggerMode } from '@prisma-gen/client';
import { describe, expect, it } from 'vitest';
import {
  CIStatus as PrismaCIStatus,
  KanbanColumn as PrismaKanbanColumn,
  PRState as PrismaPRState,
  RatchetState as PrismaRatchetState,
  RunScriptStatus as PrismaRunScriptStatus,
  SessionStatus as PrismaSessionStatus,
  WorkspaceCreationSource as PrismaWorkspaceCreationSource,
  WorkspaceMode as PrismaWorkspaceMode,
  WorkspaceStatus as PrismaWorkspaceStatus,
} from '@/shared/core';
import {
  exportedAgentSessionSchema,
  exportedUserSettingsSchema,
  exportedWorkspaceSchema,
} from './export-data.schema';

type DefWithType = {
  def?: {
    type?: string;
    innerType?: unknown;
    options?: unknown[];
    entries?: Record<string, string>;
  };
};

describe('Enum sync with Prisma schema', () => {
  // Helper to extract Zod enum options from a Zod enum schema
  const getEnumOptions = (zodEnum: unknown): string[] => {
    let enumSchema = zodEnum as DefWithType;

    // Unwrap optional/nullable wrappers (they use .def.type and .def.innerType)
    while (
      enumSchema.def?.type === 'optional' ||
      enumSchema.def?.type === 'nullable' ||
      enumSchema.def?.type === 'default'
    ) {
      enumSchema = enumSchema.def.innerType as DefWithType;
    }

    // Handle union types if any enum is wrapped by a union in the future.
    if (enumSchema.def?.type === 'union') {
      const firstOption = enumSchema.def.options?.[0];
      if (!firstOption) {
        throw new Error('Expected union schema to contain at least one option');
      }
      enumSchema = firstOption as DefWithType;
    }

    // Extract enum values from the def property
    const entries = enumSchema.def?.entries;
    if (!entries) {
      throw new Error('Expected enum schema entries to be present');
    }
    return Object.keys(entries);
  };

  it('WorkspaceStatus matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.status);
    const prismaValues = Object.values(PrismaWorkspaceStatus);
    expect(zodValues).toEqual(prismaValues);
  });

  it('WorkspaceCreationSource matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.creationSource);
    const prismaValues = Object.values(PrismaWorkspaceCreationSource);
    expect(zodValues).toEqual(prismaValues);
  });

  it('RunScriptStatus matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.runScriptStatus);
    const prismaValues = Object.values(PrismaRunScriptStatus);
    expect(zodValues).toEqual(prismaValues);
  });

  it('WorkspaceMode matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.mode);
    const prismaValues = Object.values(PrismaWorkspaceMode);
    expect(zodValues).toEqual(prismaValues);
  });

  it('defaults legacy workspace mode and auto-iteration config', () => {
    const parsed = exportedWorkspaceSchema.parse({
      id: 'ws-1',
      projectId: 'proj-1',
      name: 'Legacy Workspace',
      description: null,
      status: 'READY',
      worktreePath: null,
      branchName: null,
      isAutoGeneratedBranch: false,
      creationSource: 'MANUAL',
      creationMetadata: null,
      initErrorMessage: null,
      initOutput: null,
      initStartedAt: null,
      initCompletedAt: null,
      initRetryCount: 0,
      runScriptCommand: null,
      runScriptCleanupCommand: null,
      runScriptPid: null,
      runScriptPort: null,
      runScriptStartedAt: null,
      runScriptStatus: 'IDLE',
      prUrl: null,
      githubIssueNumber: null,
      githubIssueUrl: null,
      linearIssueId: null,
      linearIssueIdentifier: null,
      linearIssueUrl: null,
      defaultSessionProvider: 'WORKSPACE_DEFAULT',
      ratchetSessionProvider: 'WORKSPACE_DEFAULT',
      prNumber: null,
      prState: 'NONE',
      prReviewState: null,
      prCiStatus: 'UNKNOWN',
      prUpdatedAt: null,
      prCiFailedAt: null,
      prCiLastNotifiedAt: null,
      prReviewLastCheckedAt: null,
      prReviewLastCommentId: null,
      ratchetEnabled: true,
      ratchetState: 'IDLE',
      ratchetLastCheckedAt: null,
      ratchetActiveSessionId: null,
      ratchetLastCiRunId: null,
      hasHadSessions: false,
      cachedKanbanColumn: 'WAITING',
      stateComputedAt: null,
      createdAt: '2025-01-01T00:00:00.000Z',
      updatedAt: '2025-01-01T00:00:00.000Z',
    });

    expect(parsed.mode).toBe('STANDARD');
    expect(parsed.autoIterationConfig).toBeNull();
  });

  it('validates and defaults exported auto-iteration config', () => {
    const parsed = exportedWorkspaceSchema.parse({
      id: 'ws-1',
      projectId: 'proj-1',
      name: 'Auto Workspace',
      description: null,
      status: 'READY',
      worktreePath: null,
      branchName: null,
      isAutoGeneratedBranch: false,
      creationSource: 'MANUAL',
      creationMetadata: null,
      initErrorMessage: null,
      initOutput: null,
      initStartedAt: null,
      initCompletedAt: null,
      initRetryCount: 0,
      runScriptCommand: null,
      runScriptCleanupCommand: null,
      runScriptPid: null,
      runScriptPort: null,
      runScriptStartedAt: null,
      runScriptStatus: 'IDLE',
      mode: 'AUTO_ITERATION',
      autoIterationConfig: {
        testCommand: 'pnpm test',
        targetDescription: 'Improve coverage',
      },
      prUrl: null,
      githubIssueNumber: null,
      githubIssueUrl: null,
      linearIssueId: null,
      linearIssueIdentifier: null,
      linearIssueUrl: null,
      defaultSessionProvider: 'WORKSPACE_DEFAULT',
      ratchetSessionProvider: 'WORKSPACE_DEFAULT',
      prNumber: null,
      prState: 'NONE',
      prReviewState: null,
      prCiStatus: 'UNKNOWN',
      prUpdatedAt: null,
      prCiFailedAt: null,
      prCiLastNotifiedAt: null,
      prReviewLastCheckedAt: null,
      prReviewLastCommentId: null,
      ratchetEnabled: true,
      ratchetState: 'IDLE',
      ratchetLastCheckedAt: null,
      ratchetActiveSessionId: null,
      ratchetLastCiRunId: null,
      hasHadSessions: false,
      cachedKanbanColumn: 'WAITING',
      stateComputedAt: null,
      createdAt: '2025-01-01T00:00:00.000Z',
      updatedAt: '2025-01-01T00:00:00.000Z',
    });

    expect(parsed.autoIterationConfig).toEqual({
      testCommand: 'pnpm test',
      targetDescription: 'Improve coverage',
      maxIterations: 25,
      testTimeoutSeconds: 600,
      sessionRecycleInterval: 10,
    });
  });

  it('PRState matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.prState);
    const prismaValues = Object.values(PrismaPRState);
    expect(zodValues).toEqual(prismaValues);
  });

  it('CIStatus matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.prCiStatus);
    const prismaValues = Object.values(PrismaCIStatus);
    expect(zodValues).toEqual(prismaValues);
  });

  it('KanbanColumn matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.cachedKanbanColumn);
    const prismaValues = Object.values(PrismaKanbanColumn);
    expect(zodValues).toEqual(prismaValues);
  });

  it('RatchetState matches Prisma', () => {
    const zodValues = getEnumOptions(exportedWorkspaceSchema.shape.ratchetState);
    const prismaValues = Object.values(PrismaRatchetState);
    expect(zodValues).toEqual(prismaValues);
  });

  it('RatchetReviewTriggerMode matches Prisma', () => {
    const zodValues = getEnumOptions(exportedUserSettingsSchema.shape.ratchetReviewTriggerMode);
    const prismaValues = Object.values(PrismaRatchetReviewTriggerMode);
    expect(zodValues).toEqual(prismaValues);
  });

  it('SessionStatus matches Prisma', () => {
    const zodValues = getEnumOptions(exportedAgentSessionSchema.shape.status);
    const prismaValues = Object.values(PrismaSessionStatus);
    expect(zodValues).toEqual(prismaValues);
  });
});
