import type { inferRouterOutputs } from '@trpc/server';
import type { AppRouter } from '@/client/lib/trpc';
import type { WorkspaceSnapshotEntry } from '@/shared/workspace-snapshot';

type RouterOutputs = inferRouterOutputs<AppRouter>;

export type SidebarWorkspace =
  RouterOutputs['workspace']['getProjectSummaryState']['workspaces'][number];
export type KanbanWorkspace = RouterOutputs['workspace']['listWithKanbanState'][number];
export type WorkspaceDetail = RouterOutputs['workspace']['get'];

type SidebarSnapshotWorkspace = SidebarWorkspace & {
  sessionSummaries: WorkspaceSnapshotEntry['sessionSummaries'];
  snapshotComputedAt: string;
};

type CommonSnapshotWorkspace = {
  id: string;
  name: string;
  createdAt: Date;
  branchName: WorkspaceSnapshotEntry['branchName'];
  prUrl: WorkspaceSnapshotEntry['prUrl'];
  prNumber: WorkspaceSnapshotEntry['prNumber'];
  prState: WorkspaceSnapshotEntry['prState'];
  prCiStatus: WorkspaceSnapshotEntry['prCiStatus'];
  ratchetEnabled: boolean;
  ratchetState: WorkspaceSnapshotEntry['ratchetState'];
  ratchetDispatchOutcome: WorkspaceSnapshotEntry['ratchetDispatchOutcome'];
  ratchetDispatchRetryCount: number;
  runScriptStatus: WorkspaceSnapshotEntry['runScriptStatus'];
  isWorking: boolean;
  sessionSummaries: WorkspaceSnapshotEntry['sessionSummaries'];
  pendingRequestType: WorkspaceSnapshotEntry['pendingRequestType'];
  ratchetButtonAnimated: boolean;
  flowPhase: WorkspaceSnapshotEntry['flowPhase'];
  ciObservation: WorkspaceSnapshotEntry['ciObservation'];
  statusReason: WorkspaceSnapshotEntry['statusReason'];
  snapshotComputedAt: string;
};

type KanbanSnapshotExtension = Pick<
  KanbanWorkspace,
  | 'projectId'
  | 'status'
  | 'prUpdatedAt'
  | 'hasHadSessions'
  | 'cachedKanbanColumn'
  | 'kanbanColumn'
  | 'isArchived'
>;

type KanbanWorkspaceDefaults = Omit<
  KanbanWorkspace,
  keyof CommonSnapshotWorkspace | keyof KanbanSnapshotExtension
>;

function projectSnapshotToCommonWorkspace(entry: WorkspaceSnapshotEntry): CommonSnapshotWorkspace {
  return {
    id: entry.workspaceId,
    name: entry.name,
    createdAt: new Date(entry.createdAt),
    branchName: entry.branchName,
    prUrl: entry.prUrl,
    prNumber: entry.prNumber,
    prState: entry.prState,
    prCiStatus: entry.prCiStatus,
    ratchetEnabled: entry.ratchetEnabled,
    ratchetState: entry.ratchetState,
    ratchetDispatchOutcome: entry.ratchetDispatchOutcome,
    ratchetDispatchRetryCount: entry.ratchetDispatchRetryCount,
    runScriptStatus: entry.runScriptStatus,
    isWorking: entry.isWorking,
    sessionSummaries: entry.sessionSummaries,
    pendingRequestType: entry.pendingRequestType,
    ratchetButtonAnimated: entry.ratchetButtonAnimated,
    flowPhase: entry.flowPhase,
    ciObservation: entry.ciObservation,
    statusReason: entry.statusReason,
    snapshotComputedAt: entry.computedAt,
  };
}

export function projectSnapshotToSidebarWorkspace(
  entry: WorkspaceSnapshotEntry,
  existing?: SidebarWorkspace
): SidebarSnapshotWorkspace {
  return {
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    creationSource: 'MANUAL',
    stateComputedAt: null,
    ...existing,
    ...projectSnapshotToCommonWorkspace(entry),
    gitStats: entry.gitStats,
    lastActivityAt: entry.lastActivityAt,
    sidebarStatus: entry.sidebarStatus,
    cachedKanbanColumn: entry.kanbanColumn,
  };
}

function newKanbanWorkspaceDefaults(createdAt: Date): KanbanWorkspaceDefaults {
  return {
    description: null,
    worktreePath: null,
    isAutoGeneratedBranch: false,
    creationSource: 'MANUAL',
    creationMetadata: null,
    initErrorMessage: null,
    initOutput: null,
    initStartedAt: null,
    initCompletedAt: null,
    initScriptPid: null,
    initRetryCount: 0,
    runScriptCommand: null,
    runScriptPostRunCommand: null,
    runScriptCleanupCommand: null,
    runScriptPid: null,
    runScriptPort: null,
    runScriptStartedAt: null,
    githubIssueNumber: null,
    githubIssueUrl: null,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueUrl: null,
    defaultSessionProvider: 'WORKSPACE_DEFAULT',
    ratchetSessionProvider: 'WORKSPACE_DEFAULT',
    updatedAt: createdAt,
    prDiscoveryLastCheckedAt: null,
    prDiscoveryRetryCount: 0,
    prDiscoveryNextCheckAt: null,
    prReviewState: null,
    prCiFailedAt: null,
    prCiLastNotifiedAt: null,
    prReviewLastCheckedAt: null,
    prReviewLastCommentId: null,
    ratchetLastCheckedAt: null,
    ratchetActiveSessionId: null,
    ratchetLastCiRunId: null,
    stateComputedAt: null,
    mode: 'STANDARD',
    autoIterationStatus: null,
    autoIterationConfig: null,
    autoIterationProgress: null,
    autoIterationSessionId: null,
    periodicTaskId: null,
    parentWorkspaceId: null,
    agentSessions: [],
    terminalSessions: [],
  };
}

export function projectSnapshotToKanbanWorkspace(
  entry: WorkspaceSnapshotEntry,
  existing?: KanbanWorkspace
): KanbanWorkspace {
  const commonWorkspace = projectSnapshotToCommonWorkspace(entry);
  const snapshotExtension: KanbanSnapshotExtension = {
    projectId: entry.projectId,
    status: entry.status,
    prUpdatedAt: entry.prUpdatedAt ? new Date(entry.prUpdatedAt) : null,
    hasHadSessions: entry.hasHadSessions,
    cachedKanbanColumn: entry.kanbanColumn ?? existing?.cachedKanbanColumn ?? 'WAITING',
    kanbanColumn: entry.kanbanColumn,
    isArchived: existing?.isArchived ?? false,
  };

  return {
    ...newKanbanWorkspaceDefaults(commonWorkspace.createdAt),
    ...existing,
    ...commonWorkspace,
    ...snapshotExtension,
  };
}

export function mergeProjectSnapshotIntoWorkspaceDetail(
  entry: WorkspaceSnapshotEntry,
  existing: WorkspaceDetail | undefined
): WorkspaceDetail | undefined {
  if (!existing) {
    return undefined;
  }

  return {
    ...existing,
    ...projectSnapshotToCommonWorkspace(entry),
    status: entry.status,
    prUpdatedAt: entry.prUpdatedAt ? new Date(entry.prUpdatedAt) : null,
    hasHadSessions: entry.hasHadSessions,
    cachedKanbanColumn: entry.kanbanColumn ?? existing.cachedKanbanColumn,
    sidebarStatus: entry.sidebarStatus,
  };
}
