import { beforeEach, describe, expect, it, vi } from 'vitest';

const mockSetBranchNameAndClearAutoGenerated = vi.hoisted(() => vi.fn());
const mockGitCommand = vi.hoisted(() => vi.fn());
const mockGitStateInvalidate = vi.hoisted(() => vi.fn());

vi.mock('@/backend/services/workspace', () => ({
  workspaceDataService: {
    setBranchNameAndClearAutoGenerated: (...args: unknown[]) =>
      mockSetBranchNameAndClearAutoGenerated(...args),
  },
}));

vi.mock('@/backend/lib/shell', () => ({
  gitCommand: (...args: unknown[]) => mockGitCommand(...args),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

vi.mock('@/backend/services/workspace-git-state.service', () => ({
  workspaceGitStateService: { invalidate: mockGitStateInvalidate },
}));

import { branchRenameInterceptor } from './branch-rename.interceptor';

describe('branchRenameInterceptor', () => {
  const context = {
    workspaceId: 'w1',
    workingDir: '/tmp/w1',
  } as never;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('subscribes to all tool events so Codex command titles are dispatched', () => {
    expect(branchRenameInterceptor.tools).toBe('*');
  });

  it('ignores errored tool events and non-rename commands', async () => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: true },
        input: {},
      } as never,
      context
    );

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git status' },
      } as never,
      context
    );

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('updates workspace branch name and clears auto-generated flag after git branch -m', async () => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'new-branch\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -m better-name' },
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledOnce();
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'new-branch');
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/w1');
  });

  it('invalidates a rename contained in an overall failed shell command', async () => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'git branch -m renamed && false',
        output: { isError: true },
        input: {},
      } as never,
      context
    );

    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/w1');
    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('detects git branch -m when Codex provides the command as the tool name', async () => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'codex-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'git branch -m codex-name',
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'codex-name');
  });

  it.each([
    'git status && git branch -m chained-name',
    'false || git branch -m chained-name',
    'git status; git branch -m chained-name',
    'git status\ngit branch -m chained-name',
  ])('detects a branch rename in a chained shell command: %s', async (toolName) => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'chained-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'chained-name');
  });

  it.each([
    '   git branch -m nested-name',
    '(git branch -m nested-name)',
    'echo status && ( git branch -M nested-name )',
  ])('detects a branch rename with shell whitespace or subshell grouping: %s', async (toolName) => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'nested-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'nested-name');
  });

  it.each([
    "bash -c 'git branch -m shell-name'",
    'sh -c "git branch -M shell-name"',
    "git status && bash -c 'git branch -m shell-name'",
  ])('detects a branch rename executed by a shell -c payload: %s', async (toolName) => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'shell-name\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'shell-name');
  });

  it.each([
    'echo git branch -m codex-name',
    'echo "literal && git branch -m not-a-rename"',
    'rg -n "git branch -m" .',
    "rg -n '; git branch -m' .",
    'Search git branch -m',
    'echo \\; git branch -m escaped-name',
  ])('ignores a non-rename tool title containing the command text: %s', async (toolName) => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it.each([
    '#; git branch -m commented-name',
    'git status # && git branch -m commented-name',
    'echo "bash -c \'git branch -m quoted-name\'"',
    'bash -c "echo \\"literal; git branch -m quoted-name\\""',
  ])('ignores a rename that only appears in a shell comment or quoted argument: %s', async (toolName) => {
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName,
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('detects a rename on the line after a shell comment', async () => {
    mockGitCommand.mockResolvedValue({ code: 0, stdout: 'after-comment\n', stderr: '' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: '# ignored git branch -m commented-name\n git branch -m after-comment',
        output: { isError: false },
        input: {},
      } as never,
      context
    );

    expect(mockGitCommand).toHaveBeenCalledWith(['rev-parse', '--abbrev-ref', 'HEAD'], '/tmp/w1');
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith('w1', 'after-comment');
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/w1');
  });

  it('invalidates an observed successful rename even when branch lookup fails', async () => {
    mockGitCommand.mockResolvedValueOnce({ code: 1, stdout: '', stderr: 'failed' });

    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -M force-name' },
      } as never,
      context
    );

    mockGitCommand.mockResolvedValueOnce({ code: 0, stdout: '   \n', stderr: '' });
    await branchRenameInterceptor.onToolComplete!(
      {
        toolName: 'Bash',
        output: { isError: false },
        input: { command: 'git branch -M force-name' },
      } as never,
      context
    );

    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).toHaveBeenCalledTimes(2);
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/w1');
  });
});
