import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { InterceptorContext, ToolEvent } from './types';

const mockFindById = vi.fn();
const mockClearAutoGeneratedBranch = vi.fn();
const mockResetPRDiscoveryBackoff = vi.fn();
const mockSetBranchNameAndClearAutoGenerated = vi.fn();
const mockFindProjectById = vi.fn();
const mockGitCommand = vi.fn();
const mockGitStateInvalidate = vi.hoisted(() => vi.fn());

vi.mock('@/backend/services/workspace', () => ({
  workspaceDataService: {
    findById: (...args: unknown[]) => mockFindById(...args),
    clearAutoGeneratedBranch: (...args: unknown[]) => mockClearAutoGeneratedBranch(...args),
    resetPRDiscoveryBackoff: (...args: unknown[]) => mockResetPRDiscoveryBackoff(...args),
    setBranchNameAndClearAutoGenerated: (...args: unknown[]) =>
      mockSetBranchNameAndClearAutoGenerated(...args),
  },
  projectManagementService: {
    findById: (...args: unknown[]) => mockFindProjectById(...args),
  },
}));

vi.mock('@/backend/lib/shell', () => ({
  gitCommand: (...args: unknown[]) => mockGitCommand(...args),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    info: vi.fn(),
    debug: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

vi.mock('@/backend/services/workspace-git-state.service', () => ({
  workspaceGitStateService: { invalidate: mockGitStateInvalidate },
}));

import {
  createPrePushRenameInterceptor,
  prePushRenameInterceptor,
} from './pre-push-rename.interceptor';

const context: InterceptorContext = {
  sessionId: 'session-1',
  workspaceId: 'workspace-1',
  workingDir: '/tmp/workspace',
  timestamp: new Date('2026-02-20T00:00:00.000Z'),
};

function createEvent(overrides: Partial<ToolEvent>): ToolEvent {
  return {
    toolUseId: 'tool-1',
    toolName: 'Bash',
    input: {},
    ...overrides,
  };
}

describe('prePushRenameInterceptor', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/pulsar-3',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });
    mockFindProjectById.mockResolvedValue({
      id: 'project-1',
      githubOwner: 'martin-purplefish',
    });
    mockGitCommand.mockResolvedValue({ code: 0, stdout: '', stderr: '' });
    mockClearAutoGeneratedBranch.mockResolvedValue({});
    mockResetPRDiscoveryBackoff.mockResolvedValue(true);
    mockSetBranchNameAndClearAutoGenerated.mockResolvedValue({});
  });

  it('renames branch when git push detected and branch is auto-generated', async () => {
    const event = createEvent({
      input: { command: 'git push -u origin HEAD' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-rename-1',
    });

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['branch', '-m', 'martin-purplefish/fix-duplicate-branch-name'],
      '/tmp/workspace'
    );
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledOnce();
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith(
      'ws-rename-1',
      'martin-purplefish/fix-duplicate-branch-name'
    );
    expect(mockClearAutoGeneratedBranch).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/workspace');
  });

  it('only clears the auto-generated flag when the generated name already matches', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });

    const event = createEvent({
      input: { command: 'git push -u origin HEAD' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-name-matches',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).not.toHaveBeenCalled();
    expect(mockClearAutoGeneratedBranch).toHaveBeenCalledOnce();
    expect(mockClearAutoGeneratedBranch).toHaveBeenCalledWith('ws-name-matches');
  });

  it('skips when branch is not auto-generated', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });

    const event = createEvent({
      input: { command: 'git push -u origin HEAD' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-skip-not-auto',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('skips non-push commands', async () => {
    const event = createEvent({
      input: { command: 'git status' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-status-cmd',
    });

    expect(mockFindById).not.toHaveBeenCalled();
    expect(mockGitCommand).not.toHaveBeenCalled();
  });

  it('handles git rename failure gracefully', async () => {
    mockGitCommand.mockResolvedValue({
      code: 1,
      stdout: '',
      stderr: 'fatal: branch already exists',
    });

    const event = createEvent({
      input: { command: 'git push -u origin HEAD' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-git-fail',
    });

    expect(mockGitCommand).toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/workspace');
  });

  it('detects git push in cmd field', async () => {
    const event = createEvent({
      toolName: 'exec_command',
      input: { cmd: 'git push -u origin HEAD' },
    });

    await prePushRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cmd-field',
    });

    expect(mockGitCommand).toHaveBeenCalled();
  });

  it('resets PR discovery after a successful push on a named branch', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });
    const interceptor = createPrePushRenameInterceptor();
    const event = createEvent({
      toolUseId: 'tool-successful-push',
      input: { command: 'git push origin HEAD' },
    });

    await interceptor.onToolStart!(event, context);
    await interceptor.onToolComplete!(
      { ...event, output: { content: 'pushed', isError: false } },
      context
    );

    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledOnce();
    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledWith('workspace-1');
  });

  it('does not reset PR discovery after a failed push', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });
    const interceptor = createPrePushRenameInterceptor();
    const event = createEvent({
      toolUseId: 'tool-failed-push',
      input: { command: 'git push origin HEAD' },
    });

    await interceptor.onToolStart!(event, context);
    await interceptor.onToolComplete!(
      { ...event, output: { content: 'failed', isError: true } },
      context
    );

    expect(mockResetPRDiscoveryBackoff).not.toHaveBeenCalled();
  });

  it('tracks matching tool IDs independently across sessions', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });
    const interceptor = createPrePushRenameInterceptor();
    const event = createEvent({
      toolUseId: 'shared-tool-id',
      input: { command: 'git push origin HEAD' },
    });
    const firstContext = {
      ...context,
      sessionId: 'session-1',
      workspaceId: 'workspace-1',
    };
    const secondContext = {
      ...context,
      sessionId: 'session-2',
      workspaceId: 'workspace-2',
    };

    await interceptor.onToolStart!(event, firstContext);
    await interceptor.onToolStart!(event, secondContext);
    await interceptor.onToolComplete!(
      { ...event, output: { content: 'pushed', isError: false } },
      firstContext
    );
    await interceptor.onToolComplete!(
      { ...event, output: { content: 'pushed', isError: false } },
      secondContext
    );

    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledTimes(2);
    expect(mockResetPRDiscoveryBackoff).toHaveBeenNthCalledWith(1, 'workspace-1');
    expect(mockResetPRDiscoveryBackoff).toHaveBeenNthCalledWith(2, 'workspace-2');
  });

  it('clears pending push state after completion and on stop', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix duplicate branch name',
      branchName: 'martin-purplefish/fix-duplicate-branch-name',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });
    const interceptor = createPrePushRenameInterceptor();
    const event = createEvent({
      toolUseId: 'tool-cleared-push',
      input: { command: 'git push origin HEAD' },
    });
    const completion = { ...event, output: { content: 'pushed', isError: false } };

    await interceptor.onToolStart!(event, context);
    await interceptor.onToolComplete!(completion, context);
    await interceptor.onToolComplete!(completion, context);

    await interceptor.onToolStart!({ ...event, toolUseId: 'tool-stopped-push' }, context);
    interceptor.stop!();
    await interceptor.onToolComplete!({ ...completion, toolUseId: 'tool-stopped-push' }, context);

    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledOnce();
  });

  it('factory instances do not share renamed workspace state', async () => {
    const interceptorA = createPrePushRenameInterceptor();
    const interceptorB = createPrePushRenameInterceptor();
    const event = createEvent({
      input: { command: 'git push -u origin HEAD' },
    });
    const isolatedContext = { ...context, workspaceId: 'ws-factory-isolated' };

    await interceptorA.onToolStart!(event, isolatedContext);
    await interceptorB.onToolStart!(event, isolatedContext);

    expect(mockGitCommand).toHaveBeenCalledTimes(2);
  });
});
