import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { InterceptorContext, ToolEvent } from './types';

const mockFindById = vi.fn();
const mockClearAutoGeneratedBranch = vi.fn();
const mockSetBranchNameAndClearAutoGenerated = vi.fn();
const mockFindProjectById = vi.fn();
const mockGitCommand = vi.fn();
const mockGitStateInvalidate = vi.hoisted(() => vi.fn());

vi.mock('@/backend/services/workspace', () => ({
  workspaceDataService: {
    findById: (...args: unknown[]) => mockFindById(...args),
    clearAutoGeneratedBranch: (...args: unknown[]) => mockClearAutoGeneratedBranch(...args),
    setBranchNameAndClearAutoGenerated: (...args: unknown[]) =>
      mockSetBranchNameAndClearAutoGenerated(...args),
  },
  projectManagementService: {
    findById: (...args: unknown[]) => mockFindProjectById(...args),
  },
}));

vi.mock('@/backend/lib/shell', () => ({
  gitCommand: (...args: unknown[]) => mockGitCommand(...args),
}));

vi.mock('@/backend/services/logger.service', () => ({
  createLogger: () => ({
    info: vi.fn(),
    debug: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

vi.mock('@/backend/services/workspace-git-state.service', () => ({
  workspaceGitStateService: { invalidate: mockGitStateInvalidate },
}));

// Import after mocks are set up
import {
  createPrePrRenameInterceptor,
  generateBranchName,
  prePrRenameInterceptor,
} from './pre-pr-rename.interceptor';

const context: InterceptorContext = {
  sessionId: 'session-1',
  workspaceId: 'workspace-1',
  workingDir: '/tmp/workspace',
  timestamp: new Date('2026-02-17T00:00:00.000Z'),
};

function createEvent(overrides: Partial<ToolEvent>): ToolEvent {
  return {
    toolUseId: 'tool-1',
    toolName: 'Bash',
    input: {},
    ...overrides,
  };
}

describe('prePrRenameInterceptor', () => {
  afterEach(() => {
    prePrRenameInterceptor.stop?.();
  });

  beforeEach(() => {
    vi.clearAllMocks();
    prePrRenameInterceptor.start?.();
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix authentication bug',
      branchName: 'adeeshaek/dolphin-1',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });
    mockFindProjectById.mockResolvedValue({
      id: 'project-1',
      githubOwner: 'adeeshaek',
    });
    mockGitCommand.mockResolvedValue({ code: 0, stdout: '', stderr: '' });
    mockClearAutoGeneratedBranch.mockResolvedValue({});
    mockSetBranchNameAndClearAutoGenerated.mockResolvedValue({});
  });

  it('renames branch when gh pr create detected and branch is auto-generated', async () => {
    const event = createEvent({
      input: { command: 'gh pr create --title "Fix auth bug"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-rename-1',
    });

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['branch', '-m', 'adeeshaek/fix-authentication-bug'],
      '/tmp/workspace'
    );
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledOnce();
    expect(mockSetBranchNameAndClearAutoGenerated).toHaveBeenCalledWith(
      'ws-rename-1',
      'adeeshaek/fix-authentication-bug'
    );
    expect(mockClearAutoGeneratedBranch).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/workspace');
  });

  it('only clears the auto-generated flag when the generated name already matches', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix authentication bug',
      branchName: 'adeeshaek/fix-authentication-bug',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });

    const event = createEvent({
      input: { command: 'gh pr create --title "Fix auth bug"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-name-matches',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).not.toHaveBeenCalled();
    expect(mockClearAutoGeneratedBranch).toHaveBeenCalledOnce();
    expect(mockClearAutoGeneratedBranch).toHaveBeenCalledWith('ws-name-matches');
  });

  it('skips when branch is not auto-generated', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix auth',
      branchName: 'adeeshaek/fix-auth',
      isAutoGeneratedBranch: false,
      projectId: 'project-1',
    });

    const event = createEvent({
      input: { command: 'gh pr create --title "Fix auth"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-skip-not-auto',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
  });

  it('skips when workspace not found', async () => {
    mockFindById.mockResolvedValue(null);

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-not-found',
    });

    expect(mockGitCommand).not.toHaveBeenCalled();
  });

  it('skips non-pr-create commands', async () => {
    const event = createEvent({
      input: { command: 'gh pr list' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-list-cmd',
    });

    expect(mockFindById).not.toHaveBeenCalled();
    expect(mockGitCommand).not.toHaveBeenCalled();
  });

  it('handles git rename failure gracefully', async () => {
    mockGitCommand.mockResolvedValue({
      code: 1,
      stdout: '',
      stderr: 'fatal: branch already exists',
    });

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-git-fail',
    });

    expect(mockGitCommand).toHaveBeenCalled();
    expect(mockSetBranchNameAndClearAutoGenerated).not.toHaveBeenCalled();
    expect(mockGitStateInvalidate).toHaveBeenCalledWith('/tmp/workspace');
  });

  it('does not rename twice for the same workspace', async () => {
    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    const wsContext = { ...context, workspaceId: 'ws-dedup' };

    await prePrRenameInterceptor.onToolStart!(event, wsContext);
    await prePrRenameInterceptor.onToolStart!(event, wsContext);

    expect(mockGitCommand).toHaveBeenCalledTimes(1);
  });

  it('generates branch name without prefix when project has no githubOwner', async () => {
    mockFindProjectById.mockResolvedValue({ id: 'project-1', githubOwner: null });

    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-no-prefix',
    });

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['branch', '-m', 'fix-authentication-bug'],
      '/tmp/workspace'
    );
  });

  it('detects gh pr create in cmd field', async () => {
    const event = createEvent({
      toolName: 'exec_command',
      input: { cmd: 'gh pr create --title "test"' },
    });

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cmd-field',
    });

    expect(mockGitCommand).toHaveBeenCalled();
  });

  it('deletes old remote branch after successful gh pr create when refs match', async () => {
    const event = createEvent({
      toolUseId: 'tool-cleanup',
      input: { command: 'gh pr create --title "test"' },
    });

    mockGitCommand
      .mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }) // branch -m
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // rev-parse HEAD
      .mockResolvedValueOnce({
        code: 0,
        stdout: 'origin/adeeshaek/fix-authentication-bug\n',
        stderr: '',
      }) // upstream
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // old remote ref
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // new remote ref
      .mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }); // push --delete

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cleanup-1',
    });

    await prePrRenameInterceptor.onToolComplete!(
      {
        ...event,
        output: { content: 'created', isError: false },
      },
      {
        ...context,
        workspaceId: 'ws-cleanup-1',
      }
    );

    expect(mockGitCommand).toHaveBeenCalledWith(
      ['push', 'origin', '--delete', 'adeeshaek/dolphin-1'],
      '/tmp/workspace'
    );
    expect(mockGitStateInvalidate).toHaveBeenCalledTimes(2);
  });

  it('normalizes remote-prefixed branch names during remote cleanup', async () => {
    mockFindById.mockResolvedValue({
      id: 'workspace-1',
      name: 'Fix authentication bug',
      branchName: 'origin/adeeshaek/dolphin-1',
      isAutoGeneratedBranch: true,
      projectId: 'project-1',
    });

    const event = createEvent({
      toolUseId: 'tool-cleanup-prefixed',
      input: { command: 'gh pr create --title "test"' },
    });

    mockGitCommand
      .mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }) // branch -m
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // rev-parse HEAD
      .mockResolvedValueOnce({
        code: 0,
        stdout: 'origin/adeeshaek/fix-authentication-bug\n',
        stderr: '',
      }) // upstream
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // old remote ref
      .mockResolvedValueOnce({ code: 0, stdout: 'abc123\n', stderr: '' }) // new remote ref
      .mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }); // push --delete

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cleanup-prefixed',
    });

    await prePrRenameInterceptor.onToolComplete!(
      {
        ...event,
        output: { content: 'created', isError: false },
      },
      {
        ...context,
        workspaceId: 'ws-cleanup-prefixed',
      }
    );

    expect(mockGitCommand).toHaveBeenNthCalledWith(
      4,
      ['rev-parse', '--verify', '--quiet', 'refs/remotes/origin/adeeshaek/dolphin-1'],
      '/tmp/workspace'
    );
    expect(mockGitCommand).toHaveBeenNthCalledWith(
      6,
      ['push', 'origin', '--delete', 'adeeshaek/dolphin-1'],
      '/tmp/workspace'
    );
  });

  it('does not delete old remote branch when gh pr create fails', async () => {
    const event = createEvent({
      toolUseId: 'tool-cleanup-fail',
      input: { command: 'gh pr create --title "test"' },
    });

    mockGitCommand.mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }); // branch -m

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cleanup-2',
    });

    await prePrRenameInterceptor.onToolComplete!(
      {
        ...event,
        output: { content: 'failed', isError: true },
      },
      {
        ...context,
        workspaceId: 'ws-cleanup-2',
      }
    );

    expect(mockGitCommand).toHaveBeenCalledTimes(1);
  });

  it('does not throw when remote cleanup fails on tool completion', async () => {
    const event = createEvent({
      toolUseId: 'tool-cleanup-error',
      input: { command: 'gh pr create --title "test"' },
    });

    mockGitCommand.mockResolvedValueOnce({ code: 0, stdout: '', stderr: '' }); // branch -m

    await prePrRenameInterceptor.onToolStart!(event, {
      ...context,
      workspaceId: 'ws-cleanup-error',
    });

    mockGitCommand.mockRejectedValueOnce(new Error('spawn ENOENT'));

    await expect(
      prePrRenameInterceptor.onToolComplete!(
        {
          ...event,
          output: { content: 'created', isError: false },
        },
        {
          ...context,
          workspaceId: 'ws-cleanup-error',
        }
      )
    ).resolves.toBeUndefined();
  });

  it('factory instances do not share renamed workspace state', async () => {
    const interceptorA = createPrePrRenameInterceptor();
    const interceptorB = createPrePrRenameInterceptor();
    const event = createEvent({
      input: { command: 'gh pr create --title "test"' },
    });
    const isolatedContext = { ...context, workspaceId: 'ws-prepr-factory-isolated' };

    await interceptorA.onToolStart!(event, isolatedContext);
    await interceptorB.onToolStart!(event, isolatedContext);

    expect(mockGitCommand).toHaveBeenCalledTimes(2);
  });
});

describe('generateBranchName', () => {
  it('kebab-cases workspace name with prefix', () => {
    expect(
      generateBranchName({
        branchPrefix: 'adeeshaek',
        workspaceName: 'Fix Authentication Bug',
      })
    ).toBe('adeeshaek/fix-authentication-bug');
  });

  it('kebab-cases without prefix', () => {
    expect(
      generateBranchName({
        branchPrefix: '',
        workspaceName: 'Add user login',
      })
    ).toBe('add-user-login');
  });

  it('truncates long names to 30 characters', () => {
    const result = generateBranchName({
      branchPrefix: '',
      workspaceName: 'This is a very long workspace name that should be truncated',
    });
    // The slug portion (without prefix) should be at most 30 chars
    expect(result.length).toBeLessThanOrEqual(30);
  });

  it('handles special characters', () => {
    expect(
      generateBranchName({
        branchPrefix: 'user',
        workspaceName: 'Fix: the @#$ weird (bug) [123]',
      })
    ).toBe('user/fix-the-weird-bug-123');
  });

  it('returns empty string for empty workspace name', () => {
    expect(
      generateBranchName({
        branchPrefix: 'user',
        workspaceName: '',
      })
    ).toBe('');
  });

  it('strips leading and trailing hyphens', () => {
    expect(
      generateBranchName({
        branchPrefix: '',
        workspaceName: '---hello world---',
      })
    ).toBe('hello-world');
  });
});
