import { beforeEach, describe, expect, it, vi } from 'vitest';

const { mockResetPRDiscoveryBackoff, mockUpdate } = vi.hoisted(() => ({
  mockResetPRDiscoveryBackoff: vi.fn(),
  mockUpdate: vi.fn(),
}));

vi.mock('@/backend/services/workspace/resources/workspace.accessor', () => ({
  workspaceAccessor: {
    resetPRDiscoveryBackoff: (...args: unknown[]) => mockResetPRDiscoveryBackoff(...args),
    update: (...args: unknown[]) => mockUpdate(...args),
  },
}));

import { workspaceDataService } from './data.service';

describe('workspaceDataService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('sets the branch name and clears the auto-generated flag in one update', async () => {
    mockUpdate.mockResolvedValue({ id: 'workspace-1' });

    await workspaceDataService.setBranchNameAndClearAutoGenerated('workspace-1', 'my-custom-name');

    expect(mockUpdate).toHaveBeenCalledOnce();
    expect(mockUpdate).toHaveBeenCalledWith('workspace-1', {
      branchName: 'my-custom-name',
      isAutoGeneratedBranch: false,
      prDiscoveryLastCheckedAt: null,
      prDiscoveryRetryCount: 0,
      prDiscoveryNextCheckAt: null,
    });
  });

  it('delegates PR discovery backoff resets to the workspace accessor', async () => {
    mockResetPRDiscoveryBackoff.mockResolvedValue(true);

    await expect(workspaceDataService.resetPRDiscoveryBackoff('workspace-1')).resolves.toBe(true);

    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledOnce();
    expect(mockResetPRDiscoveryBackoff).toHaveBeenCalledWith('workspace-1');
  });
});
