import type { Workspace, WorkspaceProviderSelection } from '@prisma-gen/client';
import { workspaceAccessor } from '@/backend/services/workspace/resources/workspace.accessor';
import type { WorkspaceStatus } from '@/shared/core';

class WorkspaceDataService {
  findById(id: string) {
    return workspaceAccessor.findById(id);
  }

  findByIdWithProject(id: string) {
    return workspaceAccessor.findByIdWithProject(id);
  }

  exists(id: string) {
    return workspaceAccessor.exists(id);
  }

  findProviderSelection(id: string) {
    return workspaceAccessor.findProviderSelection(id);
  }

  findFixerContext(id: string) {
    return workspaceAccessor.findFixerContext(id);
  }

  findStatusSnapshot(id: string) {
    return workspaceAccessor.findStatusSnapshot(id);
  }

  findPRContext(id: string) {
    return workspaceAccessor.findPRContext(id);
  }

  findRatchetProjection(id: string) {
    return workspaceAccessor.findRawById(id);
  }

  findByProjectId(
    projectId: string,
    filters?: { status?: WorkspaceStatus; limit?: number; offset?: number }
  ) {
    return workspaceAccessor.findByProjectId(projectId, filters);
  }

  findByIdsWithProject(ids: string[]) {
    return workspaceAccessor.findByIdsWithProject(ids);
  }

  recordSessionPresence(id: string): Promise<void> {
    return workspaceAccessor.markHasHadSessions(id);
  }

  setBranchNameAndClearAutoGenerated(id: string, branchName: string) {
    return workspaceAccessor.update(id, {
      branchName,
      isAutoGeneratedBranch: false,
      prDiscoveryLastCheckedAt: null,
      prDiscoveryRetryCount: 0,
      prDiscoveryNextCheckAt: null,
    });
  }

  resetPRDiscoveryBackoff(id: string) {
    return workspaceAccessor.resetPRDiscoveryBackoff(id);
  }

  clearAutoGeneratedBranch(id: string) {
    return workspaceAccessor.update(id, {
      isAutoGeneratedBranch: false,
    });
  }

  rename(id: string, name: string) {
    return workspaceAccessor.update(id, { name });
  }

  update(
    id: string,
    data: {
      defaultSessionProvider?: WorkspaceProviderSelection;
      ratchetSessionProvider?: WorkspaceProviderSelection;
    }
  ) {
    return workspaceAccessor.update(id, {
      defaultSessionProvider: data.defaultSessionProvider,
      ratchetSessionProvider: data.ratchetSessionProvider,
    });
  }

  delete(id: string): Promise<Workspace> {
    return workspaceAccessor.delete(id);
  }
}

export const workspaceDataService = new WorkspaceDataService();
