import type { Prisma } from '@prisma-gen/client';
import {
  type RunScriptExecutionState,
  workspaceAccessor,
} from '@/backend/services/workspace/resources/workspace.accessor';
import type { RunScriptStatus } from '@/shared/core';

type RunScriptTransitionUpdate = Pick<
  Prisma.WorkspaceUpdateManyMutationInput,
  'runScriptStatus' | 'runScriptPid' | 'runScriptPort' | 'runScriptStartedAt'
>;

class WorkspaceRunScriptService {
  registerInitializedWorktree(
    workspaceId: string,
    data: {
      worktreePath: string;
      branchName: string | null;
      isAutoGeneratedBranch: boolean;
      runScriptCommand: string | null;
      runScriptPostRunCommand: string | null;
      runScriptCleanupCommand: string | null;
    }
  ) {
    return workspaceAccessor.update(workspaceId, {
      worktreePath: data.worktreePath,
      branchName: data.branchName,
      isAutoGeneratedBranch: data.isAutoGeneratedBranch,
      runScriptCommand: data.runScriptCommand,
      runScriptPostRunCommand: data.runScriptPostRunCommand,
      runScriptCleanupCommand: data.runScriptCleanupCommand,
    });
  }

  setCommands(
    workspaceId: string,
    data: {
      runScriptCommand: string | null;
      runScriptPostRunCommand: string | null;
      runScriptCleanupCommand: string | null;
    }
  ) {
    return workspaceAccessor.update(workspaceId, {
      runScriptCommand: data.runScriptCommand,
      runScriptPostRunCommand: data.runScriptPostRunCommand,
      runScriptCleanupCommand: data.runScriptCleanupCommand,
    });
  }

  findExecutionState(workspaceId: string): Promise<RunScriptExecutionState | null> {
    return workspaceAccessor.findRunScriptExecutionState(workspaceId);
  }

  getExecutionStateOrThrow(workspaceId: string): Promise<RunScriptExecutionState> {
    return workspaceAccessor.findRunScriptExecutionStateOrThrow(workspaceId);
  }

  transitionStatusIfCurrent(
    workspaceId: string,
    currentStatus: RunScriptStatus,
    data: RunScriptTransitionUpdate
  ) {
    return workspaceAccessor.casRunScriptStatusUpdate(workspaceId, currentStatus, {
      runScriptStatus: data.runScriptStatus,
      runScriptPid: data.runScriptPid,
      runScriptPort: data.runScriptPort,
      runScriptStartedAt: data.runScriptStartedAt,
    });
  }

  recoverStaleStatuses() {
    return workspaceAccessor.resetStaleRunScriptStatuses();
  }

  clearInitOutput(workspaceId: string) {
    return workspaceAccessor.clearInitOutput(workspaceId);
  }

  appendInitOutput(workspaceId: string, output: string, maxSize?: number) {
    return workspaceAccessor.appendInitOutput(workspaceId, output, maxSize);
  }

  setInitScriptPid(workspaceId: string, pid: number) {
    return workspaceAccessor.setInitScriptPid(workspaceId, pid);
  }

  clearInitScriptPid(workspaceId: string, pid: number) {
    return workspaceAccessor.clearInitScriptPid(workspaceId, pid);
  }
}

export const workspaceRunScriptService = new WorkspaceRunScriptService();
export type { RunScriptExecutionState };
