import { beforeEach, describe, expect, it, vi } from 'vitest';
import { workspaceAccessor } from '@/backend/services/workspace/resources/workspace.accessor';
import { workspaceAutoIterationService } from './workspace-auto-iteration.service';
import { workspaceRatchetService } from './workspace-ratchet.service';
import { workspaceRunScriptService } from './workspace-run-script.service';

vi.mock('@/backend/services/workspace/resources/workspace.accessor', () => ({
  workspaceAccessor: {
    findAutoIterationExecutionContext: vi.fn(),
    findRunScriptExecutionState: vi.fn(),
    findRunScriptExecutionStateOrThrow: vi.fn(),
    finishAutoIterationIfSessionMatches: vi.fn(),
    casRunScriptStatusUpdate: vi.fn(),
    recordRatchetDispatchIfEnabled: vi.fn(),
    update: vi.fn(),
  },
}));

describe('workspace state capabilities', () => {
  beforeEach(() => vi.clearAllMocks());

  it('finishes auto-iteration only when the active session still matches', async () => {
    vi.mocked(workspaceAccessor.finishAutoIterationIfSessionMatches).mockResolvedValue(true);

    await expect(
      workspaceAutoIterationService.finishSessionIfMatching('ws-1', 'session-1', 'COMPLETED')
    ).resolves.toBe(true);
    expect(workspaceAccessor.finishAutoIterationIfSessionMatches).toHaveBeenCalledWith(
      'ws-1',
      'session-1',
      'COMPLETED'
    );
  });

  it('reads only the auto-iteration execution context', async () => {
    vi.mocked(workspaceAccessor.findAutoIterationExecutionContext).mockResolvedValue({
      worktreePath: '/tmp/worktree',
      autoIterationSessionId: 'session-1',
    });

    await expect(workspaceAutoIterationService.getExecutionContext('ws-1')).resolves.toEqual({
      worktreePath: '/tmp/worktree',
      autoIterationSessionId: 'session-1',
    });
    expect(workspaceAccessor.findAutoIterationExecutionContext).toHaveBeenCalledWith('ws-1');
  });

  it('reads only run-script execution state', async () => {
    vi.mocked(workspaceAccessor.findRunScriptExecutionState).mockResolvedValue({
      runScriptStatus: 'RUNNING',
      runScriptPid: 123,
      runScriptPort: 3000,
      runScriptStartedAt: new Date('2026-01-01T00:00:00.000Z'),
    });

    await expect(workspaceRunScriptService.findExecutionState('ws-1')).resolves.toMatchObject({
      runScriptStatus: 'RUNNING',
      runScriptPid: 123,
    });
    expect(workspaceAccessor.findRunScriptExecutionState).toHaveBeenCalledWith('ws-1');
  });

  it('transitions run-script state with compare-and-swap', async () => {
    vi.mocked(workspaceAccessor.casRunScriptStatusUpdate).mockResolvedValue({ count: 1 });

    await expect(
      workspaceRunScriptService.transitionStatusIfCurrent('ws-1', 'IDLE', {
        runScriptStatus: 'STARTING',
      })
    ).resolves.toEqual({ count: 1 });
  });

  it('limits run-script transitions to run-script state fields', async () => {
    vi.mocked(workspaceAccessor.casRunScriptStatusUpdate).mockResolvedValue({ count: 1 });

    await workspaceRunScriptService.transitionStatusIfCurrent('ws-1', 'IDLE', {
      runScriptStatus: 'STARTING',
      runScriptPid: 123,
      name: 'must-not-cross-the-boundary',
    } as never);

    expect(workspaceAccessor.casRunScriptStatusUpdate).toHaveBeenCalledWith('ws-1', 'IDLE', {
      runScriptStatus: 'STARTING',
      runScriptPid: 123,
      runScriptPort: undefined,
      runScriptStartedAt: undefined,
    });
  });

  it('records ratchet dispatch only while ratcheting remains enabled', async () => {
    vi.mocked(workspaceAccessor.recordRatchetDispatchIfEnabled).mockResolvedValue(true);

    await expect(
      workspaceRatchetService.recordDispatchIfEnabled('ws-1', {
        sessionId: 'session-1',
        snapshotKey: 'snapshot-1',
        retryCount: 2,
      })
    ).resolves.toBe(true);
  });

  it('registers an initialized worktree and its run-script commands atomically', async () => {
    vi.mocked(workspaceAccessor.update).mockResolvedValue({ id: 'ws-1' } as never);

    await workspaceRunScriptService.registerInitializedWorktree('ws-1', {
      worktreePath: '/tmp/worktree',
      branchName: 'feature/task',
      isAutoGeneratedBranch: true,
      runScriptCommand: 'pnpm dev',
      runScriptPostRunCommand: null,
      runScriptCleanupCommand: 'pnpm cleanup',
    });

    expect(workspaceAccessor.update).toHaveBeenCalledWith('ws-1', {
      worktreePath: '/tmp/worktree',
      branchName: 'feature/task',
      isAutoGeneratedBranch: true,
      runScriptCommand: 'pnpm dev',
      runScriptPostRunCommand: null,
      runScriptCleanupCommand: 'pnpm cleanup',
    });
  });
});
