import type { Workspace } from '@prisma-gen/client';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { userSettingsService } from '@/backend/services/settings';
import { workspaceDataService } from '@/backend/services/workspace';
import { sessionProviderResolverService } from './session-provider-resolver.service';

vi.mock('@/backend/services/workspace');
vi.mock('@/backend/services/settings');

const createWorkspace = (overrides?: Partial<Workspace>): Workspace =>
  ({
    id: 'ws-1',
    projectId: 'project-1',
    name: 'Workspace',
    description: null,
    status: 'READY',
    worktreePath: '/tmp/worktree',
    branchName: 'feature/test',
    isAutoGeneratedBranch: false,
    creationSource: 'MANUAL',
    creationMetadata: null,
    initErrorMessage: null,
    initOutput: null,
    initStartedAt: null,
    initCompletedAt: null,
    initRetryCount: 0,
    runScriptCommand: null,
    runScriptCleanupCommand: null,
    runScriptPid: null,
    runScriptPort: null,
    runScriptStartedAt: null,
    runScriptStatus: 'IDLE',
    prUrl: null,
    githubIssueNumber: null,
    githubIssueUrl: null,
    defaultSessionProvider: 'WORKSPACE_DEFAULT',
    ratchetSessionProvider: 'WORKSPACE_DEFAULT',
    prNumber: null,
    prState: 'NONE',
    prReviewState: null,
    prCiStatus: 'UNKNOWN',
    prUpdatedAt: null,
    prCiFailedAt: null,
    prCiLastNotifiedAt: null,
    prReviewLastCheckedAt: null,
    prReviewLastCommentId: null,
    ratchetEnabled: true,
    ratchetState: 'IDLE',
    ratchetLastCheckedAt: null,
    ratchetActiveSessionId: null,
    ratchetLastCiRunId: null,
    hasHadSessions: false,
    cachedKanbanColumn: 'WAITING',
    stateComputedAt: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    ...overrides,
  }) as Workspace;

describe('sessionProviderResolverService', () => {
  beforeEach(() => {
    vi.clearAllMocks();

    vi.mocked(workspaceDataService.findById).mockResolvedValue(createWorkspace() as never);
    vi.mocked(userSettingsService.get).mockResolvedValue({
      id: 'settings-1',
      userId: 'default',
      preferredIde: 'cursor',
      customIdeCommand: null,
      playSoundOnComplete: true,
      notificationSoundPath: null,
      workspaceOrder: null,
      cachedSlashCommands: null,
      ratchetEnabled: false,
      ratchetReplyToPrComments: true,
      ratchetReviewTriggerMode: 'CHANGES_REQUESTED',
      defaultSessionProvider: 'CLAUDE',
      defaultClaudeModel: 'sonnet',
      defaultCodexModel: 'default',
      defaultClaudeReasoningEffort: null,
      defaultCodexReasoningEffort: null,
      defaultWorkspacePermissions: 'STRICT',
      ratchetPermissions: 'YOLO',
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    });
    vi.mocked(userSettingsService.getDefaultSessionProvider).mockResolvedValue('CLAUDE');
  });

  it('uses explicit provider over workspace and user defaults', async () => {
    const provider = await sessionProviderResolverService.resolveSessionProvider({
      workspaceId: 'ws-1',
      explicitProvider: 'CODEX',
    });

    expect(provider).toBe('CODEX');
    expect(workspaceDataService.findById).not.toHaveBeenCalled();
    expect(userSettingsService.getDefaultSessionProvider).not.toHaveBeenCalled();
  });

  it('uses workspace default when configured', async () => {
    vi.mocked(workspaceDataService.findById).mockResolvedValue(
      createWorkspace({ defaultSessionProvider: 'CODEX' }) as never
    );

    const provider = await sessionProviderResolverService.resolveSessionProvider({
      workspaceId: 'ws-1',
    });

    expect(provider).toBe('CODEX');
    expect(userSettingsService.getDefaultSessionProvider).not.toHaveBeenCalled();
  });

  it('falls back to user default when workspace is WORKSPACE_DEFAULT', async () => {
    const provider = await sessionProviderResolverService.resolveSessionProvider({
      workspaceId: 'ws-1',
    });

    expect(provider).toBe('CLAUDE');
    expect(userSettingsService.getDefaultSessionProvider).toHaveBeenCalledTimes(1);
  });

  it('resolves the configured model for the selected provider', async () => {
    vi.mocked(userSettingsService.getDefaultSessionProvider).mockResolvedValue('CODEX');
    vi.mocked(userSettingsService.get).mockResolvedValue({
      defaultCodexModel: 'gpt-5.3-codex',
    } as never);

    await expect(
      sessionProviderResolverService.resolveSessionDefaults({
        workspaceId: 'ws-1',
      })
    ).resolves.toEqual({
      provider: 'CODEX',
      model: 'gpt-5.3-codex',
    });
  });
});
